// devela/src/data/store/pool/_example.rs
//
//! Defines [`PoolExample`, `PoolHandleExample`].
//

use crate::pool;

pool! {
    [
        index: u8 + crate::NonMaxU8;
        generation: u16;
    ]

    #[doc = crate::_tags!(example data_structure)]
    /// An example fixed-capacity generational pool, generated by [`pool!`].
    #[doc = crate::_doc_meta!{
        location("data/store"),
        #[cfg(target_pointer_width = "32")]
        test_size_of(__: PoolExample<u8, 0> = 8|64),
        #[cfg(target_pointer_width = "32")]
        test_size_of(__: PoolExample<u8, 16> = 88|704),
        #[cfg(target_pointer_width = "32")]
        test_size_of(__: PoolExample<devela::NonZeroU8, 16> = 72|576),
        #[cfg(target_pointer_width = "64")]
        test_size_of(__: PoolExample<u8, 0> = 16|128),
        #[cfg(target_pointer_width = "64")]
        test_size_of(__: PoolExample<u8, 16> = 96|768),
        #[cfg(target_pointer_width = "64")]
        test_size_of(__: PoolExample<devela::NonZeroU8, 16> = 80|640),
    }]
    /// # Methods
    ///
    /// - Construction:
    ///   [`new`](#method.new).
    /// - Capacity:
    ///   [`capacity`](#method.capacity),
    ///   [`len`](#method.len),
    ///   [`remaining`](#method.remaining),
    ///   [`is_empty`](#method.is_empty),
    ///   [`is_full`](#method.is_full).
    /// - Access:
    ///   [`contains`](#method.contains),
    ///   [`get`](#method.get) *([_mut](#method.get_mut))*,
    ///   [`get2_mut`](#method.get2_mut).
    /// - Mutation:
    ///   [`insert`](#method.insert) *([_copy](#method.insert_copy))*,
    ///   [`replace`](#method.replace),
    ///   [`remove`](#method.remove),
    ///   [`clear`](#method.clear) *([_copy](#method.clear_copy))*.
    /// - Iteration:
    ///   [`iter`](#method.iter) *([_copy](#method.iter_mut))*,
    ///   [`handles`](#method.handles),
    ///   [`entries`](#method.entries).
    pub PoolExample;

    #[doc = crate::_tags!(example uid)]
    /// A handle into [`PoolExample`], generated by [`pool!`].
    #[doc = crate::_doc_meta!{
        location("data/store"),
        test_size_of(PoolHandleExample = 4|32),
    }]
    /// # Methods
    ///
    /// - Construction:
    ///   [`new`](#method.new),
    ///   [`from_prim`](#method.from_prim),
    ///   [`try_from_usize`](#method.try_from_usize).
    /// - Access:
    ///   [`index`](#method.index) *([_prim](#method.index_prim), [_usize](#method.index_usize))*,
    ///   [`generation`](#method.generation) *([_prim](#method.generation_prim))*.
    pub PoolHandleExample;
}
