// devela/src/data/store/pool/seq/_example.rs
//
//! Defines example sequence-pool types.
//

use crate::{NonMaxU16, pool_seq};

pool_seq! {
    [
        index: u8;
        generation: u16 + NonMaxU16;
        cell: u16;
    ]

    #[doc = crate::_tags!(example data_structure)]
    /// An example fixed-capacity sequence pool, generated by [`pool_seq!`].
    #[doc = crate::_doc_location!("data/store/pool")]
    ///
    /// Stores independently reclaimable contiguous sequences whose handles
    /// remain valid when their physical spans relocate.
    pub PoolSeqExample;

    #[doc = crate::_tags!(example uid)]
    /// A generational handle into [`PoolSeqExample`].
    #[doc = crate::_doc_location!("data/store/pool")]
    pub PoolSeqHandleExample;
}
