// devela/src/data/store/pool/seq/_example.rs
//
//! Defines example sequence-pool types.
//

use crate::{NonMaxU16, pool_seq};

pool_seq! {
    [
        index: u8;
        generation: u16 + NonMaxU16;
        cell: u16;
    ]

    #[doc = crate::_tags!(example data_structure)]
    /// An example fixed-capacity sequence pool.
    #[doc = crate::_doc_location!("data/store/pool")]
    ///
    /// Generated by [`pool_seq!`].
    ///
    /// Stores independently reclaimable contiguous sequences whose handles
    /// remain valid when their physical spans relocate.
    ///
    /// # Methods
    ///
    /// - Construction:
    ///   [`new_init`](#method.new_init).
    /// - Sequence capacity:
    ///   [`capacity`](#method.capacity),
    ///   [`len`](#method.len),
    ///   [`is_empty`](#method.is_empty),
    ///   [`remaining`](#method.remaining),
    ///   [`is_full`](#method.is_full).
    /// - Cell capacity:
    ///   [`cell_capacity`](#method.cell_capacity),
    ///   [`cell_len`](#method.cell_len),
    ///   [`allocated_cell_len`](#method.allocated_cell_len),
    ///   [`cell_remaining`](#method.cell_remaining),
    ///   [`largest_free_span`](#method.largest_free_span),
    ///   [`can_insert`](#method.can_insert),
    ///   [`is_fragmented_for`](#method.is_fragmented_for).
    /// - Sequence access:
    ///   [`contains`](#method.contains),
    ///   [`seq_len`](#method.seq_len),
    ///   [`seq_capacity`](#method.seq_capacity),
    ///   [`seq_remaining`](#method.seq_remaining),
    ///   [`get`](#method.get) *([_mut](#method.get_mut))*.
    /// - Mutation:
    ///   [`insert`](#method.insert),
    ///   [`remove`](#method.remove),
    ///   [`truncate`](#method.truncate),
    ///   [`clear_seq`](#method.clear_seq),
    ///   [`shrink_to_fit`](#method.shrink_to_fit),
    ///   [`reserve_exact`](#method.reserve_exact),
    ///   [`push`](#method.push),
    ///   [`extend_from_slice`](#method.extend_from_slice),
    ///   [`pop`](#method.pop),
    ///   [`clear`](#method.clear).
    /// - Physical packing:
    ///   [`compact`](#method.compact),
    ///   [`pack`](#method.pack).
    pub PoolSeqExample;

    #[doc = crate::_tags!(example uid)]
    /// A generational handle into [`PoolSeqExample`].
    #[doc = crate::_doc_location!("data/store/pool")]
    ///
    /// Generated by [`pool_seq!`].
    ///
    /// # Methods
    ///
    /// - Construction:
    ///   [`new`](#method.new),
    ///   [`from_prim`](#method.from_prim),
    ///   [`try_from_usize`](#method.try_from_usize).
    /// - Access:
    ///   [`index`](#method.index)
    ///   *([_prim](#method.index_prim), [_usize](#method.index_usize))*,
    ///   [`generation`](#method.generation)
    ///   *([_prim](#method.generation_prim))*.
    pub PoolSeqHandleExample;
}
