// devela/src/data/id/handle/_example.rs
//
//! Defines example handle types.
//

use crate::{handle, handle_gen, handle_span};

#[cfg(any(test, feature = "_docs_examples"))]
handle! {
    [
        index: u8 + crate::NonMaxU8;
        kind: u8;
        revision: u16;
    ]

    #[doc = crate::_tags!(example uid)]
    /// An example general handle, generated by [`handle!`].
    #[doc = crate::_doc_meta!{
        location("data"),
        test_size_of(HandleExample = 4|32; niche Option),
    }]
    /// Demonstrates three independently represented components:
    /// - a niche-aware `index`,
    /// - a `kind` discriminator,
    /// - and a `revision` value.
    ///
    /// Their interpretation and external validity are left to the resolver.
    ///
    /// ```
    /// # use devela::{handle, NonMaxU8};
    /// handle! {
    ///     [
    ///         index: u8 + NonMaxU8;
    ///         kind: u8;
    ///         revision: u16;
    ///     ]
    ///     /// An example general handle, generated by [`handle!`].
    ///     pub HandleExample;
    /// }
    /// ```
    pub HandleExample;
}

#[cfg(any(test, feature = "_docs_examples"))]
handle_gen! {
    [
        index: u8;
        generation: u16 + crate::NonMaxU16;
    ]

    #[doc = crate::_tags!(example uid)]
    /// An example generational handle, generated by [`handle_gen!`].
    #[doc = crate::_doc_meta!{
        location("data"),
        test_size_of(HandleGenExample = 4|32; niche Option),
    }]
    /// Demonstrates a generational handle with niche-aware index and generation fields.
    pub HandleGenExample;
}
#[cfg(any(test, feature = "_docs_examples"))]
handle_span! {
    [ offset: u8 + crate::NonMaxU8; ]

    #[doc = crate::_tags!(example uid)]
    /// An example span handle, generated by [`handle_span!`].
    #[doc = crate::_doc_meta!{
        location("data"),
        test_size_of(HandleSpanExample = 2|16; niche Option),
    }]
    ///
    /// Demonstrates a minimal span-handle using niche-aware `u8` storage.
    pub HandleSpanExample;
}
