// devela/src/data/id/handle/_example.rs
//
//! Defines [`HandleSpanExample`].
//
// TODO
// - IndexHandleExample
// - SpanHandleExample
// - GenHandleExample
// - ScopedHandleExample
// - PageSlotHandleExample

use crate::handle;

#[cfg(any(test, feature = "_docs_examples"))]
handle! {
    [offset: u8 + crate::NonMaxU8; ]

    #[doc = crate::_tags!(example uid)]
    /// An example handle generated by [`handle!`].
    #[doc = crate::_doc_meta!{location("data")}]
    ///
    /// Demonstrates a minimal span-handle using niche-aware `u8` storage.
    pub HandleSpanExample;
}
