// devela/src/data/id/handle/_example.rs
//
//! Defines [`HandleSpanExample`].
//
// TODO
// - IndexHandleExample
// - SpanHandleExample
// - GenHandleExample
// - ScopedHandleExample
// - PageSlotHandleExample

use crate::handle_span;

#[cfg(any(test, feature = "_docs_examples"))]
handle_span! {
    [offset: u8 + crate::NonMaxU8; ]

    #[doc = crate::_tags!(example uid)]
    /// An example handle generated by [`handle_span!`].
    #[doc = crate::_doc_meta!{
        location("data"),
        test_size_of(HandleSpanExample = 2|16; niche Option),
    }]
    ///
    /// Demonstrates a minimal span-handle using niche-aware `u8` storage.
    pub HandleSpanExample;
}
