// devela/src/data/id/_example.rs
//
//! Defines [`IdSeqU64Example`].
//

use crate::id_seq;

id_seq![
    #[doc = crate::_tags!(example uid construction)]
    /// An example sequential identifier using a `u64`, generated by [`id_seq`].
    #[doc = crate::_doc_meta!{
        location("data/id"),
        test_size_of(IdSeqU64Example = 8|64)
    }]
    /// Its counter starts at `u64::MIN + 1`
    /// and increments with each new identifier generated.
    ///
    /// The implementation guards against wrap-around after `u64::MAX`
    /// by returning `None` in the checked methods,
    /// or panicking in the unchecked methods.
    pub IdSeqU64Example, u64
];
