# devela workspace manifest
# ==============================================================================
# https://doc.rust-lang.org/cargo/reference/manifest.html
# https://doc.rust-lang.org/nightly/cargo/CHANGELOG.html
#
## Table of Contents
#
# * [workspace]
#   * [members]
#   * [package]
#
# * [workspace.dependencies]
#
# * [profile.*]
# * [workspace.lints]
#

[workspace]
# ==============================================================================
# https://doc.rust-lang.org/cargo/reference/workspaces.html
resolver = "3"

default-members = ["crates/devela"]

members = [ # In sync with crates/devela/build/environment.rs
	# core
    "crates/devela",         # main integrated library
    "crates/devela/macros",  # required internal proc-macro support

	# downstream ecosystem
    # "crates/bridge",       # FFI and ABI bridges
    # "crates/extend",       # ecosystem extensions and adapters
    # "crates/micros",       # MCU, board, and embedded hardware

    # "build/post",          # post-build processing

    # incubators: opt-in individually
    # "progs/…",
    # "games/…",
]
exclude = [
	"crates/sentry",         # public-API and behavior validation
]


[workspace.package]
# Centralizes member-package metadata.
# ------------------------------------------------------------------------------
version = "0.30.0-wip" # In sync with docs/changelog.md
rust-version = "1.98.1" # In sync with README.md, .github/workflows/check.yml, tools/rustfmt
documentation = "https://docs.rs/devela/"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
license = "MIT OR Apache-2.0"
edition = "2024"


[workspace.dependencies]
# Centralizes dependency declarations used by workspace members.
# ------------------------------------------------------------------------------
devela_macros      = { version = "0.30.0-wip", path = "./crates/devela/macros" }
#devela_buildpost   = { version = "0.30.0-wip", path = "./build/post" }

#* optional external dependencies *#

[workspace.dependencies.atomic] # https://crates.io/crates/atomic (unsafe)
version = "0.6.1" # ✗ https://github.com/Amanieu/atomic-rs/commits/master/
default-features = false # 4 https://docs.rs/crate/atomic/latest/features
features = ["fallback"]

[workspace.dependencies.hashbrown] # https://crates.io/crates/hashbrown (unsafe)
version = "0.17" # ✓ https://github.com/rust-lang/hashbrown/blob/master/CHANGELOG.md
default-features = false # 14 https://docs.rs/crate/hashbrown/latest/features
features = ["default-hasher", "inline-more"]

[workspace.dependencies.jiff] # https://crates.io/crates/jiff (safe ± few & checked)
version = "0.2" # ✓ https://github.com/BurntSushi/jiff/blob/master/CHANGELOG.md
default-features = false # 10 https://docs.rs/crate/jiff/latest/features
# features = [""] # https://docs.rs/jiff/latest/jiff/#crate-features

[workspace.dependencies.log] # https://crates.io/crates/log (optional unsafe)
version = "0.4.29" # ✓ https://github.com/rust-lang/log/blob/master/CHANGELOG.md
default-features = false # 25 https://docs.rs/crate/log/latest/features
# features = ["kv"]

[workspace.dependencies.memchr] # https://crates.io/crates/memchr (unsafe)
version = "2.8" # ✗ https://github.com/BurntSushi/memchr/commits/master/
default-features = false # 9 https://docs.rs/crate/memchr/latest/features

[workspace.dependencies.portable-atomic] # https://crates.io/crates/portable-atomic (unsafe)
version = "1.15" # ✓ https://github.com/taiki-e/portable-atomic/blob/main/CHANGELOG.md
default-features = false # 11 https://docs.rs/crate/portable-atomic/latest/features
# https://docs.rs/portable-atomic/1.11.0/portable_atomic/#optional-features
features = ["fallback", "float"]

[workspace.dependencies.portable-atomic-util] # https://crates.io/crates/portable-atomic-util (unsafe)
version = "0.2" # ✓ https://github.com/taiki-e/portable-atomic-util/blob/main/CHANGELOG.md
default-features = false # 3 https://docs.rs/crate/portable-atomic-util/latest/features

[workspace.dependencies.rand_core] # https://crates.io/crates/rand_core (safe)
version = "0.10" # ✓ https://github.com/rust-random/rand_core/blob/master/CHANGELOG.md
default-features = false # 3 https://docs.rs/crate/rand_core/latest/features

[workspace.dependencies.raw-cpuid] # https://crates.io/crates/raw-cpuid (unsafe)
version = "11.6" # ✓ https://github.com/gz/rust-cpuid/blob/master/CHANGELOG.md
default-features = false # 9 https://docs.rs/crate/raw-cpuid/latest/features

[workspace.dependencies.safe_arch] # https://crates.io/crates/safe_arch (unsafe)
version = "1.0" # ✗ https://github.com/Lokathor/safe_arch/commits/main/
default-features = false # 2 https://docs.rs/crate/safe_arch/latest/features

[workspace.dependencies.simdutf8] # https://crates.io/crates/simdutf8 (unsafe)
version = "0.1" # ✓ https://github.com/rusticstuff/simdutf8/blob/main/CHANGELOG.md
default-features = false # 6 https://docs.rs/crate/simdutf8/latest/features
# features = [] # https://github.com/rusticstuff/simdutf8/blob/main/Cargo.toml
# WAIT: [const_methods](https://github.com/rusticstuff/simdutf8/pull/111) text::str::namespace

[workspace.dependencies.wide] # https://crates.io/crates/wide (unsafe)
version = "1.6" # ✓ https://github.com/Lokathor/wide/blob/main/changelog.md
default-features = false # 2 https://docs.rs/crate/wide/latest/features


# profiles
# ==============================================================================
# https://doc.rust-lang.org/cargo/reference/profiles.html
# https://doc.rust-lang.org/stable/rustc/codegen-options/
# https://nnethercote.github.io/perf-book/build-configuration.html
# https://doc.rust-lang.org/stable/cargo/guide/build-performance.html

[profile.dev]
debug = "line-tables-only"
# codegen-backend = "cranelift"

[profile.dev.package."*"]
debug = false
# codegen-backend = "llvm"
# opt-level = 3

[profile.debugging]
inherits = "dev"
debug = true

[profile.dev-lto]
inherits = "dev"
lto = "thin" # false, thin, fat, off

[profile.release-lto]
inherits = "release"
lto = "thin"

[profile.bench]
opt-level = 3
debug = false
lto = true
codegen-units = 1

[profile.wasm]
inherits = "release"
# https://rustwasm.github.io/docs/book/reference/code-size.html
opt-level = "s"      # Optimize for size
lto = true           # Enable link-time optimizations
codegen-units = 1    # Improve optimization at the cost of compile time
panic = "abort"      # Reduce binary size (no unwinding)
strip = true         # Remove debug symbols for smaller binaries


[workspace.lints]
# ==============================================================================
# https://doc.rust-lang.org/cargo/reference/manifest.html#the-lints-section
# WAIT: [override lints](https://github.com/rust-lang/cargo/issues/13157) (can't customize)

[workspace.lints.rust]
# https://doc.rust-lang.org/stable/nightly-rustc/rustc_lint/builtin/index.html#constants
# ------------------------------------------------------------------------------
# https://doc.rust-lang.org/rustc/lints/listing/deny-by-default.html
# WAIT: [lazy_type_alias](https://github.com/rust-lang/rust/issues/112792)
type_alias_bounds = "deny" # detects bounds in type aliases
unsafe_op_in_unsafe_fn = "deny" # unsafe use inside unsafe fn without unsafe block
#
# https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html
missing_docs = "warn" # missing docs for public items
# missing_debug_implementations = "warn" # missing Debug impls for public items
#
# https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html
stable_features = "allow" # a feature attribute that has since been made stable
unused_features = "allow" # unused crate-level features (1.96)
unknown_lints = "allow" # unrecognized lint attributes

[workspace.lints.rustdoc]
# https://doc.rust-lang.org/rustdoc/lints.html
# ------------------------------------------------------------------------------

# missing_crate_level_docs = "warn" # no documentation at the crate root (or any binary)
#
# broken_intra_doc_links = "allow" # NOTE: conditionally allowed in /src/_.rs & other places
redundant_explicit_links = "allow" # (primitive aliases (char) need the explicit reference)

# [workspace.lints.cargo] WAIT:1.100:cargo-lints
# # https://doc.rust-lang.org/cargo/reference/lints.html
# # ------------------------------------------------------------------------------
# non_kebab_case_bins = "warn"

[workspace.lints.clippy]
# https://doc.rust-lang.org/clippy/lints.html
# https://rust-lang.github.io/rust-clippy/master/index.html
# https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md
# ------------------------------------------------------------------------------
# --- deny ---
#
## [pedantic]
enum_glob_use = "deny" # `use Enum::*`
## [style]
missing_safety_doc = "deny" # no `# Safety` section in public unsafe fns
#
# --- warn ---
#
all = { level = "warn", priority = -1 } # (the default set of clippy lints)
## [complexity]
map_unwrap_or = "warn" # usage of result|option.map(_).unwrap_or[_else](_)
## [pedantic]
bool_to_int_with_if = "warn" # using an if statement to convert a bool to an int
cloned_instead_of_copied = "warn" # usage of cloned() where copied() could be used
ignored_unit_patterns = "warn" # Checks for usage of _ in patterns of type ()
float_cmp = "warn" # (in-)equality comparisons on floating-point values
manual_let_else = "warn" # cases where let...else could be used
manual_string_new = "warn" # usage of "" to create a String
ptr_cast_constness = "warn" # as casts between raw pointers that change their constness
# NOTE: not compatible with the is! macro w/o being able to ignore it in an expr:
# WAIT: [stmt_expr_attributes](https://github.com/rust-lang/rust/issues/15701)
# redundant_else = "warn" // else blocks that can be removed without changing semantics
same_functions_in_if_condition = "warn" # consecutive ifs with the same function call
semicolon_if_nothing_returned = "warn" # expr returns () but it's not followed by ;
single_match_else = "warn" # 2 arms in match where an if let else will usually suffice
trivially_copy_pass_by_ref = "warn" # fns with ref args that could be passed by value
unnested_or_patterns = "warn" # unnested or-patterns, (Some(a)|Some(b) vs Some(a|b))
unreadable_literal = "warn" #  long integral or float does not contain underscores
## [restriction]
default_union_representation = "warn" # union declared without #[repr(C)]
# doc_paragraphs_missing_punctuation = "warn" # doc paragraphs not ending with punctuation
empty_structs_with_brackets = "warn" # structs without fields, with brackets
# if_then_some_else_none = "warn" # if-else that could be written using bool::then[_some]
float_cmp_const = "warn" # (in-)equality comparisons on const floating-point values
#
# --- allow ---
#
## [correctness]
approx_constant = "allow" # floating-point approximating constants (are more precise in crate)
## [style]
collapsible_if = "allow" # nested if statements
doc_lazy_continuation = "allow" # markdown lazy paragraph continuations
mixed_attributes_style = "allow" # items with mixed (inner/outer) attributes
module_inception = "allow" # modules with the same name as its parent
needless_doctest_main = "allow" # doctests with a main fn (imported from examples)
nonstandard_macro_braces = "allow" # non-conventional braces on well-stablished macros
wrong_self_convention = "allow" # `is_` methods having an owned self
## [suspicious]
empty_docs = "allow" # empty documentation

[workspace.lints.rust.unexpected_cfgs]
# WAIT: [override lints](https://github.com/rust-lang/cargo/issues/13157) (move down to [lints])
# https://dev-doc.rust-lang.org/nightly/unstable-book/compiler-flags/check-cfg.html
# https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html
# https://doc.rust-lang.org/rustc/check-cfg.html
# ------------------------------------------------------------------------------
level = "warn"
check-cfg = [ # Allowed configuration flags:
	# Defined if the library is compiled as the primary package (not a dependency).
	'cfg(cargo_primary_package)',
	#
	# Allows excluding tests from being run, more concisely:
	'cfg(__exclude_test)',
	#
	# Expect more pointer widths.
	'cfg(target_pointer_width, values("8", "128"))',
	# Expect more target vendors. In sync with src/sys/env/namespace.rs:
	'cfg(target_vendor, values("vex"))', # WAIT
	#
	# Target cfg aliases. In sync with build/main/alias.rs
	"cfg(any_target_arch_linux)", # target_arch = x86_64 | x86 | arm | aarch64 | riscv32 | riscv64
	"cfg(any_target_arch_riscv)", # target_arch = riscv32 | riscv64
	"cfg(linux_syscall_target)", # supported Linux arch + target_os = linux | none
	#
	# devela_macros diagnostic policy flags:
	# --------------------------------------------------------------------------
	# These flags customize devela_macros policy diagnostics.
	#
	# devela_macros_warnings="allow"  -> suppress macro policy warnings
	# devela_macros_warnings="warn"   -> emit macro policy warnings, default
	# devela_macros_warnings="deny"   -> promote macro policy warnings to errors
	'cfg(devela_macros_warnings, values("allow", "warn", "deny"))',
	#
	# devela_macros_errors="warn"     -> downgrade intended policy errors to warnings
	# devela_macros_errors="deny"     -> emit macro policy errors, default
	'cfg(devela_macros_errors, values("warn", "deny"))',
	#
	# Nightly flags hierarchy (gating unstable functionality):
	# --------------------------------------------------------------------------
	# They are prefixed with `nightly_`.
	# Enabling any of these will set the `nightly··` reflection flag.
	# In sync with: src/_.rs, build/main/features.rs && docs/nightly.md.
	#
	## Links
	# - https://doc.rust-lang.org/unstable-book/library-features.html
	# - https://releases.rs/
	# - tools/release_dates.rs
	# - docs/nightly.md
	"cfg(nightly)", # [12] (in sync with build/main/features.rs::FLAGS_NIGHTLY & src/_.rs)
		#
		# Unstable nightly features without clear stabilization timeline
		"cfg(nightly_unstable)",
			# WAIT: [allocator_api](https://github.com/rust-lang/rust/issues/32838)
			# - https://reloaded-project.github.io/Reloaded-III/Research/Demystifying-Rust-Allocators.html
			# NOTE:dep features: "hashbrown?/nightly"]
			"cfg(nightly_allocator)", # allocator_api
			#
			# WAIT: [explicit_tail_calls](https://github.com/rust-lang/rust/issues/112788)
			"cfg(nightly_become)", # explicit_tail_calls WARN:incomplete_features (commented out in src/_.rs)
			#
			# WAIT: [autodiff](https://github.com/rust-lang/rust/issues/124509)
			# https://rust-lang.zulipchat.com/#narrow/channel/390790-wg-autodiff
			# "cfg(nightly_autodiff)", # autodiff FLAG_DISABLED:nightly_autodiff
			#
			# WAIT: [coroutines](https://github.com/rust-lang/rust/issues/43122)
			"cfg(nightly_coro)", # coroutines, coroutine_trait, iter_from_coroutine
			#
			# WAIT: [doc_cfg](https://github.com/rust-lang/rust/issues/43781)
			# LINK: https://github.com/rust-lang/rfcs/blob/master/text/3631-rustdoc-cfgs-handling.md
			# WAIT: [doc_notable_trait](https://github.com/rust-lang/rust/issues/45040)
			"cfg(nightly_doc)",
			#
			# WAIT: [f16_and_f128](https://github.com/rust-lang/rust/issues/116909)
			# WAIT: [re-export](https://github.com/rust-lang/rust/issues/116909#issuecomment-2595319840)
			"cfg(nightly_float)", # f16, f128
			#
			# WAIT: [portable_simd](https://github.com/rust-lang/rust/issues/86656)
			"cfg(nightly_simd)", # portable_simd
		#
		# nightly features expected to stabilize soon:
		"cfg(nightly_stable)",
			"cfg(nightly_stable_1_99)",
			"cfg(nightly_stable_1_100)",
			"cfg(nightly_stable_1_101)",
			"cfg(nightly_stable_1_102)",
			"cfg(nightly_stable_later)",
	#
	# Auto-enabled reflection flags from build/main/features.rs (23)
	# --------------------------------------------------------------------------
	# general: (4)
	"cfg(unsafe··, safe··, nightly··, dep··)",
	# data: (5)
	'cfg(data··)',
	# geom: (1)
	'cfg(geom··)',
	# lang: (2)
	'cfg(lang··, ffi··)',
	# media: (1)
	'cfg(media··, visual··)',
	# num: (1)
	'cfg(num··)',
	# org: (1)
	'cfg(org··)',
	# phys: (1)
	'cfg(phys··)',
	# run: (1)
	'cfg(run··)',
	# sys: (2)
	'cfg(sys··, mem··)',
    # text: (1)
    'cfg(text··)',
	# ui: (1)
	'cfg(ui··)',
	# vita: (1)
	'cfg(vita··)',
	# work: (1)
	'cfg(work··)',
	#
	# Auto-enabled native availability flags from build/main/native.rs (2)
	# --------------------------------------------------------------------------
	'cfg(ffi_alsa··)',     # alsa
	'cfg(ffi_xcb_shm··)',  # x11
]
