#!/bin/bash
#
# Runs rustfmt and clippy before a git commit.
#
# To configure git locally to use these hooks:
# $ git config core.hooksPath "./utils/git_hooks"

#* CONFIG *#

# commands
CLIPPY="cargo +stable clippy" # for the whole project
# CLIPPY="cargo +nightly clippy" # more buggy

# paths
SCRIPT_DIR=$(dirname "$0")
CRATE_ROOT=$(readlink -f "$SCRIPT_DIR/../..") # absolute path to the root


#* RUSTFMT *#

RUSTFMT_CHECK_SCRIPT="$CRATE_ROOT/utils/rustfmt"
"$RUSTFMT_CHECK_SCRIPT" check changed exclude || exit $?


#* CLIPPY *#

$CLIPPY --version &>/dev/null || { echo "clippy not available"; exit 1; }
# $CLIPPY -- --deny warnings
# $CLIPPY
result=$?
printf "[pre_commit] $CLIPPY → "
if [ $result != 0 ]; then
	printf "\033[0;31merror\033[0m\n"
	exit 1
else
	printf "\033[0;32mOK\033[0m\n"
fi
