[workspace]

[package]
name = "mcu_msp430_g2231"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
msp430-rt = "0.4.1" # TEMP

[dependencies.devela_micros]
path = "../../../.."
default-features = false

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
panic = "abort"
