// devela/src/data/topol/graph/adj/_example.rs

use crate::{NonMaxU8, NonMaxU16, graph_adj};

graph_adj! {
    [
        vertex: u8 + NonMaxU8;
        edge: u16 + NonMaxU16;
    ]

    #[doc = crate::_tags!(example data_structure topol)]
    /// An example fixed-capacity adjacency graph.
    #[doc = crate::_doc_meta!{
        location("data/topol/graph"),
        #[cfg(target_pointer_width = "32")]
        test_size_of(__: GraphAdjExample<0, 0> = 4|32),
        #[cfg(target_pointer_width = "32")]
        test_size_of(__: GraphAdjExample<4, 4> = 28|224),
        #[cfg(target_pointer_width = "64")]
        test_size_of(__: GraphAdjExample<0, 0> = 8|64),
        #[cfg(target_pointer_width = "64")]
        test_size_of(__: GraphAdjExample<4, 4> = 32|256),
    }]
    /// Generated by [`graph_adj!`].
    ///
    /// # Methods
    ///
    /// - Construction: [`new`](#method.new).
    /// - Capacity:
    ///   [`vertex_count`](#method.vertex_count),
    ///   [`edge_count`](#method.edge_count),
    ///   [`edge_capacity`](#method.edge_capacity),
    ///   [`edge_remaining`](#method.edge_remaining),
    ///   [`is_empty`](#method.is_empty),
    ///   [`is_full`](#method.is_full).
    /// - Handles:
    ///   [`vertex`](#method.vertex), [`edge`](#method.edge),
    ///   [`contains_vertex`](#method.contains_vertex),
    ///   [`contains_edge`](#method.contains_edge).
    /// - Mutation:
    ///   [`add_edge`](#method.add_edge), [`clear`](#method.clear).
    /// - Adjacency:
    ///   [`first_out_edge`](#method.first_out_edge),
    ///   [`next_out_edge`](#method.next_out_edge),
    ///   [`edge_target`](#method.edge_target).
    /// - Queries:
    ///   [`has_edge`](#method.has_edge),
    ///   [`out_degree`](#method.out_degree).
    /// - Iteration:
    ///   [`out_edges`](#method.out_edges),
    ///   [`neighbors`](#method.neighbors).
    pub GraphAdjExample;

    #[doc = crate::_tags!(example uid topol)]
    /// A vertex handle into [`GraphAdjExample`].
    #[doc = crate::_doc_meta!{
        location("data/topol/graph"),
        test_size_of(GraphAdjVertexExample = 1|8; niche Option),
    }]
    /// Generated by [`graph_adj!`].
    pub GraphAdjVertexExample;

    #[doc = crate::_tags!(example uid topol)]
    /// An edge handle into [`GraphAdjExample`].
    #[doc = crate::_doc_meta!{
        location("data/topol/graph"),
        test_size_of(GraphAdjEdgeExample = 2|16; niche Option),
    }]
    /// Generated by [`graph_adj!`].
    pub GraphAdjEdgeExample;
}

#[cfg(feature = "alloc")]
graph_adj! {
    [
        vertex: u8 + NonMaxU8;
        edge: u16 + NonMaxU16;
    ]

    #[doc = crate::_tags!(example data_structure topol)]
    /// An example allocating adjacency graph.
    #[doc = crate::_doc_meta!{
        location("data/topol/graph"),
        #[cfg(target_pointer_width = "32")]
        test_size_of(GraphAdjAllocExample = 24|192),
        #[cfg(target_pointer_width = "64")]
        test_size_of(GraphAdjAllocExample = 48|384),
    }]
    /// Generated by [`graph_adj!`].
    ///
    /// # Methods
    ///
    /// - Construction:
    ///   [`new`](#method.new), [`with_capacity`](#method.with_capacity).
    /// - Capacity:
    ///   [`vertex_count`](#method.vertex_count),
    ///   [`edge_count`](#method.edge_count),
    ///   [`edge_capacity`](#method.edge_capacity),
    ///   [`edge_remaining`](#method.edge_remaining),
    ///   [`is_empty`](#method.is_empty),
    ///   [`is_full`](#method.is_full).
    /// - Handles:
    ///   [`vertex`](#method.vertex), [`edge`](#method.edge),
    ///   [`contains_vertex`](#method.contains_vertex),
    ///   [`contains_edge`](#method.contains_edge).
    /// - Mutation:
    ///   [`add_edge`](#method.add_edge), [`clear`](#method.clear).
    /// - Adjacency:
    ///   [`first_out_edge`](#method.first_out_edge),
    ///   [`next_out_edge`](#method.next_out_edge),
    ///   [`edge_target`](#method.edge_target).
    /// - Queries:
    ///   [`has_edge`](#method.has_edge),
    ///   [`out_degree`](#method.out_degree).
    /// - Iteration:
    ///   [`out_edges`](#method.out_edges),
    ///   [`neighbors`](#method.neighbors).
    pub GraphAdjAllocExample: alloc;

    #[doc = crate::_tags!(example uid topol)]
    /// A vertex handle into [`GraphAdjAllocExample`].
    #[doc = crate::_doc_meta!{
        location("data/topol/graph"),
        test_size_of(GraphAdjAllocVertexExample = 1|8; niche Option),
    }]
    /// Generated by [`graph_adj!`].
    pub GraphAdjAllocVertexExample;

    #[doc = crate::_tags!(example uid topol)]
    /// An edge handle into [`GraphAdjAllocExample`].
    #[doc = crate::_doc_meta!{
        location("data/topol/graph"),
        test_size_of(GraphAdjAllocEdgeExample = 2|16; niche Option),
    }]
    /// Generated by [`graph_adj!`].
    pub GraphAdjAllocEdgeExample;
}
