// devela/src/data/store/intern/string/_example.rs
//
//! Defines string interner examples.
//

use crate::intern_string;

intern_string! {
    [
        index: u8 + crate::NonMaxU8;
        cursor: u16 + crate::NonMaxU16;
    ]

    #[doc = crate::_tags!(example data_structure)]
    /// An example fixed-capacity UTF-8 string interner.
    #[doc = crate::_doc_meta!{
        location("data/store/intern", struct InternStringExample),
    }]
    /// Generated by [`intern_string!`].
    ///
    /// Equal strings are canonicalized to the same compact symbol.
    /// Canonical strings are retained as packed UTF-8 bytes and indexed
    /// through an open-addressed lookup table.
    ///
    /// The three const parameters independently configure the maximum number
    /// of canonical strings, packed UTF-8 bytes, and lookup slots:
    ///
    /// `InternStringExample<STRINGS, BYTES, SLOTS>`.
    ///
    /// `SLOTS` must be at least `STRINGS`.
    ///
    /// # Methods
    ///
    /// - Representation limits:
    ///   [`MAX_CAPACITY`](#associatedconstant.MAX_CAPACITY),
    ///   [`MAX_BYTE_CAPACITY`](#associatedconstant.MAX_BYTE_CAPACITY).
    /// - Construction: [`new`](#method.new).
    /// - Canonical string capacity:
    ///   [`capacity`](#method.capacity), [`len`](#method.len),
    ///   [`is_empty`](#method.is_empty).
    /// - Lookup capacity:
    ///   [`slot_capacity`](#method.slot_capacity).
    /// - Byte storage:
    ///   [`byte_capacity`](#method.byte_capacity),
    ///   [`byte_len`](#method.byte_len),
    ///   [`byte_remaining`](#method.byte_remaining).
    /// - Access:
    ///   [`contains`](#method.contains), [`get`](#method.get),
    ///   [`find`](#method.find), [`as_bytes`](#method.as_bytes).
    /// - Canonicalization:
    ///   [`can_intern`](#method.can_intern), [`intern`](#method.intern).
    /// - Reclamation:
    ///   [`clear`](#method.clear).
    /// - Iteration:
    ///   [`iter`](#method.iter), [`symbols`](#method.symbols),
    ///   [`entries`](#method.entries).
    pub InternStringExample;

    #[doc = crate::_tags!(example uid)]
    /// A canonical string symbol for [`InternStringExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/intern", struct InternStringSymbolExample),
        test_size_of(InternStringSymbolExample = 1|8; niche Option),
    }]
    /// Generated by [`intern_string!`] and [`handle!`][crate::handle].
    ///
    /// The symbol contains only the canonical string index. It carries no
    /// interner-instance identity or generation.
    ///
    #[doc = crate::_DOC_HANDLE_INDEX_METHODS!()]
    pub InternStringSymbolExample;
}

#[cfg(feature = "alloc")]
intern_string! {
    [
        index: u8 + crate::NonMaxU8;
        cursor: u16 + crate::NonMaxU16;
    ]

    #[doc = crate::_tags!(example data_structure)]
    /// An example allocating UTF-8 string interner.
    #[doc = crate::_doc_meta!{
        location("data/store/intern", struct InternStringAllocExample),
        #[cfg(target_pointer_width = "32")]
        test_size_of(InternStringAllocExample = 36|288; niche Option),
        #[cfg(target_pointer_width = "64")]
        test_size_of(InternStringAllocExample = 72|576; niche Option),
    }]
    /// Generated by [`intern_string!`].
    ///
    /// Canonical strings and packed UTF-8 bytes use growable storage.
    /// The open-addressed lookup table also grows and rehashes when full.
    ///
    /// String, byte, and lookup-slot capacities may be reserved independently.
    ///
    /// # Methods
    ///
    /// - Representation limits:
    ///   [`MAX_CAPACITY`](#associatedconstant.MAX_CAPACITY),
    ///   [`MAX_BYTE_CAPACITY`](#associatedconstant.MAX_BYTE_CAPACITY).
    /// - Construction:
    ///   [`new`](#method.new), [`with_capacity`](#method.with_capacity).
    /// - Canonical string capacity:
    ///   [`capacity`](#method.capacity), [`len`](#method.len),
    ///   [`is_empty`](#method.is_empty).
    /// - Lookup capacity:
    ///   [`slot_capacity`](#method.slot_capacity).
    /// - Byte storage:
    ///   [`byte_capacity`](#method.byte_capacity),
    ///   [`byte_len`](#method.byte_len),
    ///   [`byte_remaining`](#method.byte_remaining).
    /// - Access:
    ///   [`contains`](#method.contains), [`get`](#method.get),
    ///   [`find`](#method.find), [`as_bytes`](#method.as_bytes).
    /// - Canonicalization:
    ///   [`can_intern`](#method.can_intern), [`intern`](#method.intern).
    /// - Reclamation:
    ///   [`clear`](#method.clear).
    /// - Iteration:
    ///   [`iter`](#method.iter), [`symbols`](#method.symbols),
    ///   [`entries`](#method.entries).
    pub InternStringAllocExample: alloc;

    #[doc = crate::_tags!(example uid)]
    /// A canonical string symbol for [`InternStringAllocExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/intern", struct InternStringAllocSymbolExample),
        test_size_of(InternStringAllocSymbolExample = 1|8; niche Option),
    }]
    /// Generated by [`intern_string!`] and [`handle!`][crate::handle].
    ///
    /// The symbol contains only the canonical string index. It remains stable
    /// when the interner grows or rehashes its lookup table.
    ///
    #[doc = crate::_DOC_HANDLE_INDEX_METHODS!()]
    pub InternStringAllocSymbolExample;
}
