// devela/src/data/store/pool/item/_example.rs
//
//! Defines [`PoolExample`, `PoolHandleExample`].
//

use crate::pool;

pool! {
    [
        index: u8 + crate::NonMaxU8;
        generation: u16;
    ]

    #[doc = crate::_tags!(example data_structure)]
    /// An example fixed-capacity generational pool.
    #[doc = crate::_doc_meta!{
        location("data/store/pool", struct PoolExample),
        #[cfg(target_pointer_width = "32")]
        test_size_of(__: PoolExample<u8, 0> = 8|64; niche !Option),
        #[cfg(target_pointer_width = "32")]
        test_size_of(__: PoolExample<u8, 16> = 88|704; niche Option),
        #[cfg(target_pointer_width = "32")]
        test_size_of(__: PoolExample<devela::NonZeroU8, 16> = 72|576; niche Option),
        #[cfg(target_pointer_width = "64")]
        test_size_of(__: PoolExample<u8, 0> = 16|128; niche !Option),
        #[cfg(target_pointer_width = "64")]
        test_size_of(__: PoolExample<u8, 16> = 96|768; niche Option),
        #[cfg(target_pointer_width = "64")]
        test_size_of(__: PoolExample<devela::NonZeroU8, 16> = 80|640; niche Option),
    }]
    /// Generated by [`pool!`].
    ///
    /// # Methods
    ///
    /// - Construction:
    ///   [`new`](#method.new).
    /// - Capacity:
    ///   [`capacity`](#method.capacity),
    ///   [`len`](#method.len),
    ///   [`is_empty`](#method.is_empty),
    ///   [`remaining`](#method.remaining),
    ///   [`is_full`](#method.is_full).
    /// - Access:
    ///   [`contains`](#method.contains),
    ///   [`get`](#method.get) *([_mut](#method.get_mut))*,
    ///   [`get2_mut`](#method.get2_mut).
    /// - Mutation:
    ///   [`insert`](#method.insert) *([_copy](#method.insert_copy))*,
    ///   [`replace`](#method.replace),
    ///   [`remove`](#method.remove),
    ///   [`clear`](#method.clear) *([_copy](#method.clear_copy))*.
    /// - Iteration:
    ///   [`iter`](#method.iter) *([_mut](#method.iter_mut))*,
    ///   [`handles`](#method.handles),
    ///   [`entries`](#method.entries) *([_mut](#method.entries_mut))*.
    pub PoolExample;

    #[doc = crate::_tags!(example uid)]
    /// A handle into [`PoolExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/pool", struct PoolHandleExample),
        test_size_of(PoolHandleExample = 4|32; niche Option),
    }]
    /// Generated by [`pool!`].
    ///
    #[doc = crate::_DOC_HANDLE_GEN_METHODS!()]
    pub PoolHandleExample;
}

#[cfg(feature = "alloc")]
pool! {
    [
        index: u8 + crate::NonMaxU8;
        generation: u16;
    ]

    #[doc = crate::_tags!(example data_structure)]
    /// An example allocated generational pool.
    #[doc = crate::_doc_meta!{
        location("data/store/pool", struct PoolAllocExample),
        #[cfg(target_pointer_width = "32")]
        test_size_of(__: PoolAllocExample<u8> = 40|320; niche Option),
        #[cfg(target_pointer_width = "64")]
        test_size_of(__: PoolAllocExample<u8> = 80|640; niche Option),
    }]
    /// Generated by [`pool!`].
    ///
    /// # Methods
    ///
    /// - Construction:
    ///   [`new`](#method.new),
    ///   [`with_capacity`](#method.with_capacity).
    /// - Capacity:
    ///   [`capacity`](#method.capacity),
    ///   [`slot_count`](#method.slot_count),
    ///   [`len`](#method.len),
    ///   [`is_empty`](#method.is_empty),
    ///   [`remaining`](#method.remaining),
    ///   [`is_full`](#method.is_full).
    /// - Access:
    ///   [`contains`](#method.contains),
    ///   [`get`](#method.get) *([_mut](#method.get_mut))*,
    ///   [`get2_mut`](#method.get2_mut).
    /// - Mutation:
    ///   [`insert`](#method.insert),
    ///   [`replace`](#method.replace),
    ///   [`remove`](#method.remove),
    ///   [`clear`](#method.clear).
    /// - Iteration:
    ///   [`iter`](#method.iter) *([_mut](#method.iter_mut))*,
    ///   [`handles`](#method.handles),
    ///   [`entries`](#method.entries) *([_mut](#method.entries_mut))*.
    pub PoolAllocExample: alloc;

    #[doc = crate::_tags!(example uid)]
    /// A handle into [`PoolAllocExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/pool", struct PoolAllocHandleExample),
        test_size_of(PoolAllocHandleExample = 4|32; niche Option),
    }]
    /// Generated by [`pool!`].
    ///
    #[doc = crate::_DOC_HANDLE_GEN_METHODS!()]
    pub PoolAllocHandleExample;
}
