# devela/examples/sys/hw/mcu/board/arduino/nano/Cargo.toml

[workspace]

[package]
name = "arduino-nano-examples"
# version = "0.0.0"
edition = "2024"
publish = false

[dependencies.devela]
path = "../../../../../../.."
default-features = false
features = ["mcu", "unsafe_mmio"]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"

[profile.debug]
panic = "abort"

[lints.cargo]
non_kebab_case_bins = "allow"
