[package]
name = "sentry-log"
edition.workspace = true
publish.workspace = true


[features]
std = ["devela/std"]
android = ["std", "devela/android"]
avr = [
    "dep:devela_micros",
    "devela_micros/arduino_nano",
    "devela_micros/unsafe_mmio",
]
web = ["devela/web"]


[dependencies]
devela.workspace = true
devela_micros = { workspace = true, optional = true }


[[bin]]
name = "stderr"
required-features = ["std"]

[[bin]]
name = "android"
required-features = ["android"]

[[bin]]
name = "avr"
required-features = ["avr"]

[[bin]]
name = "web"
required-features = ["web"]
