// devela/src/geom/affine/_.rs
//
#![doc = crate::_DOC_GEOM_AFFINE!()] // public
#![doc = crate::_doc!(modules: crate::geom; affine)]
#![doc = crate::_doc!(flat:"geom")]
#![doc = crate::_doc!(hr)]
//

crate::mods_in! {
    // mod_ frame; // Affine reference frames and coordinate systems
    // mod_ map; // Affine maps combining linear transformation and translation
    mod_ point; // Positions in affine space without metric or unit semantics
    mod_ simplex; // Minimal affine cells generated by ordered points
    // mod_ transform; // Semantic affine transformations applied to geometric entities
}
crate::mods_out! { // _mods
    _mods {
        pub use super::{
            // frame::_all::*,
            // map::_all::*,
            point::_all::{Point, Point2, Point3},
            simplex::_all::{Simplex, SimplexFacetView, SimplexFacetIter},
            // transform::_all::*,
        };
    }
}
