// devela/src/geom/affine/simplex.rs
//
//! Defines [`Simplex`].
//

use crate::{Point, is};

#[doc = crate::_tags!(geom)]
/// An ordered, possibly degenerate simplex in `D`-dimensional affine space.
#[doc = crate::_doc_meta!{location("geom/affine")}]
///
/// A simplex is generated by `V` ordered [`Point`]s. Its dimension implied by
/// the vertex count is `V - 1`; therefore a structurally valid simplex requires:
///
/// - at least one vertex: `V > 0`,
/// - no more than `D + 1` vertices: `V - 1 <= D`.
///
/// The vertex order is significant. It can later determine orientation,
/// facet signs, winding, interpolation coordinates, and oriented boundaries.
///
/// # Degeneracy
///
/// This type does not verify that its vertices are affinely independent.
/// Consequently, it can represent degenerate simplices whose actual affine
/// dimension is smaller than `V - 1`.
///
/// Degeneracy is deliberately treated as a geometric property to query, not
/// as a storage invariant. This keeps construction generic over scalar types
/// and independent of matrix, rank, tolerance, and solver facilities.
///
/// # Dimensions
///
/// `D` is the dimension of the ambient affine space.
///
/// `V` is the number of stored vertices:
/// - `V = 1`: point simplex,
/// - `V = 2`: segment simplex,
/// - `V = 3`: triangle simplex,
/// - `V = 4`: tetrahedral simplex.
///
/// Empty simplices are not represented.
///
/// # Example
/// ```
/// # use devela::{Point, Simplex};
/// let triangle = Simplex::<i32, 2, 3>::new([
///     Point::new([0, 0]),
///     Point::new([4, 0]),
///     Point::new([0, 3]),
/// ]);
///
/// assert_eq!(triangle.dimension(), 2);
/// assert_eq!(triangle.codimension(), 0);
/// assert!(triangle.is_full_dimensional());
/// assert_eq!(triangle.vertex(1), Some(&Point::new([4, 0])));
/// ```
#[must_use]
#[non_exhaustive] // prevent downstream struct literals to enforce constructor invariants
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Simplex<T, const D: usize, const V: usize> {
    /// The ordered vertices generating this simplex.
    pub vertices: [Point<T, D>; V],
}

#[rustfmt::skip]
impl<T, const D: usize, const V: usize> Simplex<T, D, V> {
    /// The dimension of the ambient affine space.
    pub const AMBIENT_DIMENSION: usize = D;
    /// The number of stored vertices.
    pub const VERTEX_COUNT: usize = V;
    /// Creates a simplex from its ordered vertices.
    ///
    /// This validates only the relationship between `D` and `V`. It does not
    /// test whether the vertices are affinely independent.
    ///
    /// # Panics
    ///
    /// Panics if:
    ///
    /// - `V == 0`, or
    /// - `V - 1 > D`.
    pub const fn new(vertices: [Point<T, D>; V]) -> Self {
        assert!(V > 0, "a simplex requires at least one vertex");
        assert!(V - 1 <= D, "the simplex dimension exceeds its ambient dimension");
        Self { vertices }
    }
    /// Returns the dimension implied by the number of vertices.
    ///
    /// This is `V - 1`. A degenerate simplex can have a smaller actual affine
    /// dimension.
    #[must_use]
    pub const fn dimension(&self) -> usize { V - 1 }

    /// Returns the simplex codimension in its ambient space.
    ///
    /// This is `D - (V - 1)`.
    #[must_use]
    pub const fn codimension(&self) -> usize { D - (V - 1) }

    /// Returns whether the simplex dimension equals the ambient dimension.
    ///
    /// This describes its structural dimensions only. A full-dimensional
    /// simplex can still be geometrically degenerate.
    #[must_use]
    pub const fn is_full_dimensional(&self) -> bool { V - 1 == D }

    /// Returns the vertex at `index`, or `None` when it is out of bounds.
    #[must_use]
    pub const fn vertex(&self, index: usize) -> Option<&Point<T, D>> {
        is! { index < V, Some(&self.vertices[index]), None }
    }
    /// Returns the vertex at `index` mutably, or `None` when it is out of bounds.
    pub const fn vertex_mut(&mut self, index: usize) -> Option<&mut Point<T, D>> {
        is! { index < V, Some(&mut self.vertices[index]), None }
    }

    /// Maps every ordered vertex into another point type.
    ///
    /// The ambient dimension and vertex count remain unchanged.
    #[must_use]
    pub fn map_vertices<U>(self, map: impl FnMut(Point<T, D>) -> Point<U, D>) -> Simplex<U, D, V> {
        Simplex { vertices: self.vertices.map(map), }
    }
}

#[cfg(test)]
mod _test {
    use crate::{Point, Simplex};

    const TRIANGLE: Simplex<i32, 2, 3> =
        Simplex::new([Point::new([0, 0]), Point::new([4, 0]), Point::new([0, 3])]);

    #[test]
    fn structural_dimensions() {
        assert_eq!(TRIANGLE.dimension(), 2);
        assert_eq!(TRIANGLE.codimension(), 0);
        assert!(TRIANGLE.is_full_dimensional());
        let embedded = Simplex::<i32, 3, 3>::new([
            Point::new([0, 0, 0]),
            Point::new([1, 0, 0]),
            Point::new([0, 1, 0]),
        ]);
        assert_eq!(embedded.dimension(), 2);
        assert_eq!(embedded.codimension(), 1);
        assert!(!embedded.is_full_dimensional());
    }
    #[test]
    fn preserves_vertex_order() {
        assert_eq!(TRIANGLE.vertex(0), Some(&Point::new([0, 0])));
        assert_eq!(TRIANGLE.vertex(1), Some(&Point::new([4, 0])));
        assert_eq!(TRIANGLE.vertex(2), Some(&Point::new([0, 3])));
        assert_eq!(TRIANGLE.vertex(3), None);
    }
    #[test]
    fn permits_degeneracy() {
        let point = Point::new([2, 3]);
        let simplex = Simplex::<i32, 2, 3>::new([point, point, point]);
        assert_eq!(simplex.dimension(), 2);
        assert_eq!(&simplex.vertices, &[point, point, point]);
    }
    #[test]
    fn mutates_vertices_explicitly() {
        let mut simplex = TRIANGLE;
        *simplex.vertex_mut(1).unwrap() = Point::new([5, 0]);
        assert_eq!(simplex.vertex(1), Some(&Point::new([5, 0])));
    }
    #[test]
    fn maps_vertices() {
        let mapped = TRIANGLE
            .map_vertices(|point| Point::new(point.coords.map(|component| component as i64)));
        assert_eq!(
            mapped.vertices,
            [Point::new([0_i64, 0]), Point::new([4_i64, 0]), Point::new([0_i64, 3]),]
        );
    }
    #[test]
    #[should_panic(expected = "at least one vertex")]
    fn rejects_empty_simplex() {
        let _ = Simplex::<i32, 2, 0>::new([]);
    }
    #[test]
    #[should_panic(expected = "exceeds its ambient dimension")]
    fn rejects_excess_dimension() {
        let _ = Simplex::<i32, 1, 3>::new([Point::new([0]), Point::new([1]), Point::new([2])]);
    }
}
