[build]
target = "z80-unknown-none-elf"

[target.z80-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tspectrum48.x",
    "-C", "llvm-args=-z80-warn-stack-align-padding=0",
    "-A", "linker-messages",
]
