// devela/src/data/store/key/map/_example.rs
//
//! Example static maps generated by [`map!`].
//!
//! Defines [`MapStaticConstU8Example`], [`MapStaticU8Example`], and [`MapStaticTypeIdExample`].
//

use crate::map;

map! {
    #[doc = crate::_tags!(example data_structure)]
    /// Example fixed-capacity map with `u8` keys and const operations.
    #[doc = crate::_doc_meta!{
        location("data/store/key", struct MapStaticConstU8Example),
        test_size_of(__: MapStaticConstU8Example<u8, u32, 4> = 20|160; niche !Option),
    }]
    /// Uses `u8::MIN` and `u8::MAX` as the empty and tombstone markers,
    /// and [`HasherFx`][crate::HasherFx] as the default hasher.
    ///
    /// # Main methods
    /// - Construction: [`new`][Self::new].
    /// - Access: [`get`][Self::get], [`get_ref`][Self::get_ref],
    ///   [`get_mut`][Self::get_mut], [`entry`][Self::entry].
    /// - Mutation: [`insert`][Self::insert], [`insert_move`][Self::insert_move],
    ///   [`remove`][Self::remove].
    /// - State: [`len`][Self::len], [`capacity`][Self::capacity],
    ///   [`is_empty`][Self::is_empty], [`is_full`][Self::is_full].
    /// - Maintenance: [`should_rebuild`][Self::should_rebuild],
    ///   [`rebuild`][Self::rebuild], [`rebuilt`][Self::rebuilt].
    pub const MapStaticConstU8Example, KEY: u8
}
map! {
    #[doc = crate::_tags!(example data_structure)]
    /// Example fixed-capacity runtime map with `u8` keys.
    #[doc = crate::_doc_meta!{
        location("data/store/key", struct MapStaticU8Example),
        test_size_of(__: MapStaticU8Example<u8, u32, 4> = 24|192; niche !Option),
    }]
    /// Unlike [`MapStaticConstU8Example`], its empty and tombstone markers
    /// are stored in each map value and its operations need not be const.
    ///
    /// # Main methods
    /// - Construction: [`new`][Self::new], [`default`][Default::default].
    /// - Access: [`get`][Self::get], [`get_ref`][Self::get_ref],
    ///   [`get_mut`][Self::get_mut], [`entry`][Self::entry].
    /// - Mutation: [`insert`][Self::insert], [`insert_move`][Self::insert_move],
    ///   [`remove`][Self::remove], [`replace`][Self::replace].
    /// - State: [`len`][Self::len], [`capacity`][Self::capacity],
    ///   [`deleted_count`][Self::deleted_count].
    /// - Maintenance: [`should_rebuild`][Self::should_rebuild],
    ///   [`rebuild`][Self::rebuild], [`rebuilt`][Self::rebuilt].
    pub MapStaticU8Example, KEY: u8
}
map! {
    #[doc = crate::_tags!(example data_structure)]
    /// Example fixed-capacity map keyed by Rust types.
    #[doc = crate::_doc_meta!{
        location("data/store/key", struct MapStaticTypeIdExample),
        test_size_of(__: MapStaticTypeIdExample<devela::TypeId, u32, 4> = 112|896; niche !Option),
    }]
    /// Type identities are represented by 64-bit hashes of [`TypeId`][crate::TypeId].
    /// It extends the runtime map with type-oriented accessors.
    ///
    /// # Type methods
    /// - [`type_id_hash`][Self::type_id_hash]
    /// - [`insert_type`][Self::insert_type]
    /// - [`get_type`][Self::get_type]
    /// - [`get_ref_type`][Self::get_ref_type]
    /// - [`get_mut_type`][Self::get_mut_type]
    /// - [`remove_type`][Self::remove_type]
    pub typeid MapStaticTypeIdExample
}
