# devela_micros manifest
# ==============================================================================

[lib]
path = "src/_.rs"
bench = false

[package]
name = "devela_micros"
build = "build/_.rs"
description = "Microcontroller, board, and embedded hardware support for devela"
repository = "https://github.com/andamira/devela/tree/main/crates/micros"
documentation = "https://docs.rs/devela_micros"
rust-version.workspace = true
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
categories = ["development-tools", "embedded", "hardware-support", "no-std"]
keywords = ["dev", "extension"]
autoexamples = false
publish = false
include = [
	"/Cargo.toml",
	"/LICENSE*",
	"/build/**/*.rs", "/src/**/*.rs",
	"/build/**/*.md", "/src/**/*.md",
	## exclusions
	"!**/_wip/**",
]

[package.metadata.docs.rs]
no-default-features = true
features = ["_docs", "__publish"]
rustc-args = [
    "--cfg", "nightly_doc",
    "--cfg", "nightly",
]
rustdoc-args = [
    "--cfg", "nightly_doc",
    "--cfg", "nightly",
    "--generate-link-to-definition",
    "--html-in-header", "./src/_doc/header.html",
]


[features]

#* Development features *#
# ------------------------------------------------------------------------------

__dbg = ["devela/__dbg"] # shows extra debugging information
__publish = ["devela/__publish"] # enabled when publishing to crates.io or docs.rs
__docs_internal = ["devela/__docs_internal"] # enables documentation for internal items
__exclude_test = [] # excludes specific examples from being tested
__disable_native_libs = [] # disables native libraries from being detected


#* Environment features *#
# ------------------------------------------------------------------------------

alloc = ["devela/alloc"]


#* Module features *#
# ------------------------------------------------------------------------------

all = ["mcu_all", "board_all", "device_all"]

# microcontrollers

mcu = []
mcu_all = ["avr_all", "esp32_all"]

	avr = ["mcu"]
	avr_all = ["atmega328p"]

		atmega328p = ["avr"]

	esp32 = ["mcu"]
	esp32_all = ["esp32c3", "esp32c6", "esp32s3"]

		esp32c3 = ["esp32"]
		esp32c6 = ["esp32"]
		esp32s3 = ["esp32"]

# boards

board = []
board_all = [
	"board_avr_all",
	"board_esp32_all",
]
	board_avr = ["board", "avr"]
	board_avr_all = ["arduino_nano"]

		arduino_nano = ["board_avr", "atmega328p"]

	board_esp32 = ["board", "esp32"]
	board_esp32_all = ["supermini_oled042"]

		# c6_touch_lcd147 = ["board_esp32", "esp32c6"]
		supermini_oled042 = ["board_esp32", "esp32c3", "ssd13xx"]


# devices

device = []
device_all = [
	"audio_all", "comm_all", "display_all", "input_all",
	"motion_all", "power_all", "sensor_all", "vision_all"
]

audio = ["device"]
audio_all = []
	#

comm = ["device"]
comm_all = ["comm"]
	# winc1500 = ["comm"]

display = ["device"]
display_all = ["ssd13xx"]
	ssd13xx = ["display"] # ssd1306, ssd1315

input = ["device"]
input_all = []
	#

motion = ["device"]
motion_all = []
	# pca9685 = ["motion"]
	# tb6612 = ["motion"]

power = ["device"]
power_all = []
	#

sensor = ["device"]
sensor_all = []
	# mhz19 = ["sensor"]

vision = ["device"]
vision_all = []
	# lepton35 = ["vision"]


#* Safety features *#
# ------------------------------------------------------------------------------

safest = ["safe", "devela/safest"]

safe = ["devela/safe"]

unsafe = [
	"unsafe_hint", # permit architecture-specific CPU instructions
	"unsafe_mmio" # permit direct hardware-register access
	]
	unsafe_hint = ["devela/unsafe_hint"]
	unsafe_mmio = ["devela/unsafe_mmio"]


#* Scope features *#
# ------------------------------------------------------------------------------

media = ["draw", "font", "image"]
	draw = ["devela/draw"]
	font = ["devela/font"]
	image = ["devela/image"]

time = ["devela/time"]

#* _docs scope *#
# ---------------

_docs_nodep = ["all", "unsafe", "media", "time"] # + alloc
_docs = ["_docs_nodep"]


[dependencies]
# ==============================================================================
devela = { workspace = true, features = ["hw"] }


[badges]
# ==============================================================================
maintenance.status = "experimental"

[lints]
workspace = true


# examples inside /examples/*
# ==============================================================================
# [[example]]
# name = ""
