// devela/src/data/store/arena/typed/_example.rs
//
//! Defines typed arena examples.
//

use crate::arena;

arena! {
    [index: u8 + crate::NonMaxU8;]

    #[doc = crate::_tags!(example data_structure)]
    /// An example fixed-capacity typed arena, generated by [`arena!`].
    #[doc = crate::_doc_meta!{location("data/store")}]
    /// # Methods
    ///
    /// - Construction: [`new`](#method.new).
    /// - Capacity:
    ///   [`capacity`](#method.capacity), [`len`](#method.len),
    ///   [`is_empty`](#method.is_empty), [`remaining`](#method.remaining),
    ///   [`is_full`](#method.is_full).
    /// - Access:
    ///   [`contains`](#method.contains),
    ///   [`get`](#method.get) *([_mut](#method.get_mut))* and
    ///   [`get2_mut`](#method.get2_mut).
    /// - Mutation:
    ///   [`insert`](#method.insert) *([_copy](#method.insert_copy))*.
    /// - Reclamation:
    ///   [`mark`](#method.mark),
    ///   [`rollback`](#method.rollback) *([_copy](#method.rollback_copy))* and
    ///   [`clear`](#method.clear) *([_copy](#method.clear_copy))*.
    /// - Iteration: [`iter`](#method.iter) *([_mut](#method.iter_mut))*.
    pub ArenaExample;

    #[doc = crate::_tags!(example uid)]
    /// An index handle into [`ArenaExample`], generated by [`arena!`].
    #[doc = crate::_doc_meta!{location("data/store")}]
    pub ArenaHandleExample;

    #[doc = crate::_tags!(example data_structure)]
    /// A rollback mark for [`ArenaExample`], generated by [`arena!`].
    #[doc = crate::_doc_meta!{location("data/store")}]
    pub ArenaMarkExample;
}

#[cfg(feature = "alloc")]
arena! {
    [index: u8 + crate::NonMaxU8;]

    #[doc = crate::_tags!(example data_structure)]
    /// An example allocating typed arena, generated by [`arena!`].
    #[doc = crate::_doc_meta!{location("data/store")}]
    /// # Methods
    ///
    /// - Construction:
    ///   [`new`](#method.new), [`with_capacity`](#method.with_capacity).
    /// - Capacity:
    ///   [`capacity`](#method.capacity), [`len`](#method.len),
    ///   [`is_empty`](#method.is_empty), [`remaining`](#method.remaining),
    ///   [`is_full`](#method.is_full).
    /// - Access:
    ///   [`contains`](#method.contains),
    ///   [`get`](#method.get) *([_mut](#method.get_mut))* and
    ///   [`get2_mut`](#method.get2_mut).
    /// - Mutation: [`insert`](#method.insert).
    /// - Reclamation:
    //   [`mark`](#method.mark), [`rollback`](#method.rollback),
    ///   `mark`, `rollback`,
    ///   [`clear`](#method.clear).
    /// - Iteration: [`iter`](#method.iter) *([_mut](#method.iter_mut))*.
    pub ArenaAllocExample: alloc;

    #[doc = crate::_tags!(example uid)]
    /// An index handle into [`ArenaAllocExample`], generated by [`arena!`].
    #[doc = crate::_doc_meta!{location("data/store")}]
    pub ArenaAllocHandleExample;

    // #[doc = crate::_tags!(example data_structure)]
    // /// A rollback mark for [`ArenaAllocExample`], generated by [`arena!`].
    // #[doc = crate::_doc_meta!{location("data/store")}]
    // pub ArenaAllocMarkExample;
}
