// devela/src/data/store/arena/typed/_example.rs
//
//! Defines typed arena examples.
//

use crate::arena;

arena! {
    [index: u8 + crate::NonMaxU8;]

    #[doc = crate::_tags!(example data_structure)]
    /// An example fixed-capacity typed arena.
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaExample),
        test_size_of(ArenaExample<bool, 7> = 8|64; niche Option),
        test_size_of(ArenaExample<i8, 7> = 15|120; niche Option),
    }]
    /// Generated by [`arena!`].
    ///
    /// # Methods
    ///
    /// - Construction: [`new`](#method.new).
    /// - Capacity:
    ///   [`capacity`](#method.capacity), [`len`](#method.len),
    ///   [`is_empty`](#method.is_empty), [`remaining`](#method.remaining),
    ///   [`is_full`](#method.is_full).
    /// - Access:
    ///   [`contains`](#method.contains),
    ///   [`get`](#method.get) *([_mut](#method.get_mut))* and
    ///   [`get2_mut`](#method.get2_mut).
    /// - Mutation:
    ///   [`insert`](#method.insert) *([_copy](#method.insert_copy))*.
    /// - Reclamation:
    ///   [`mark`](#method.mark),
    ///   [`rollback`](#method.rollback) *([_copy](#method.rollback_copy))* and
    ///   [`clear`](#method.clear) *([_copy](#method.clear_copy))*.
    /// - Iteration: [`iter`](#method.iter) *([_mut](#method.iter_mut))*.
    pub ArenaExample;

    #[doc = crate::_tags!(example uid)]
    /// An index handle into [`ArenaExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaHandleExample),
        test_size_of(ArenaHandleExample = 1|8; niche Option),
    }]
    /// Generated by [`arena!`].
    ///
    #[doc = crate::_DOC_HANDLE_INDEX_METHODS!()]
    pub ArenaHandleExample;

    #[doc = crate::_tags!(example data_structure)]
    /// A rollback mark for [`ArenaExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaMarkExample),
        test_size_of(ArenaMarkExample = 1|8; niche Option),
    }]
    /// Generated by [`arena!`].
    pub ArenaMarkExample;
}

#[cfg(feature = "alloc")]
arena! {
    [index: u8 + crate::NonMaxU8;]

    #[doc = crate::_tags!(example data_structure)]
    /// An example allocating typed arena.
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaAllocExample),
        #[cfg(target_pointer_width = "32")]
        test_size_of(ArenaAllocExample<bool> = 12|96; niche Option),
        #[cfg(target_pointer_width = "64")]
        test_size_of(ArenaAllocExample<bool> = 24|192; niche Option),
    }]
    /// Generated by [`arena!`].
    ///
    /// # Methods
    ///
    /// - Construction:
    ///   [`new`](#method.new), [`with_capacity`](#method.with_capacity).
    /// - Capacity:
    ///   [`capacity`](#method.capacity), [`len`](#method.len),
    ///   [`is_empty`](#method.is_empty), [`remaining`](#method.remaining),
    ///   [`is_full`](#method.is_full).
    /// - Access:
    ///   [`contains`](#method.contains),
    ///   [`get`](#method.get) *([_mut](#method.get_mut))* and
    ///   [`get2_mut`](#method.get2_mut).
    /// - Mutation: [`insert`](#method.insert).
    /// - Reclamation:
    ///   [`mark`](#method.mark), [`rollback`](#method.rollback),
    ///   [`clear`](#method.clear).
    /// - Iteration: [`iter`](#method.iter) *([_mut](#method.iter_mut))*.
    pub ArenaAllocExample: alloc;

    #[doc = crate::_tags!(example uid)]
    /// An index handle into [`ArenaAllocExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaAllocHandleExample),
        test_size_of(ArenaAllocHandleExample = 1|8; niche Option),
    }]
    /// Generated by [`arena!`].
    ///
    #[doc = crate::_DOC_HANDLE_INDEX_METHODS!()]
    pub ArenaAllocHandleExample;

    #[doc = crate::_tags!(example data_structure)]
    /// A rollback mark for [`ArenaAllocExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaAllocMarkExample),
        #[cfg(target_pointer_width = "32")]
        test_size_of(ArenaAllocMarkExample = 4|32; niche !Option),
        #[cfg(target_pointer_width = "64")]
        test_size_of(ArenaAllocMarkExample = 8|64; niche !Option),
    }]
    /// Generated by [`arena!`].
    pub ArenaAllocMarkExample;
}
