// devela/src/data/topol/link/_example.rs
//
//! Defines [`LinkExample`].

use crate::{NonMaxU8, NonMaxU16, link};

link! {
    [
        next: u8 + NonMaxU8;
        prev: u8 + NonMaxU8;
        parent: u16 + NonMaxU16;
    ]

    #[doc = crate::_tags!(example data_structure topol)]
    /// An example set of independent optional links.
    #[doc = crate::_doc_meta!{
        location("data/topol/link", struct LinkExample),
        test_size_of(LinkExample = 4|32; niche !Option),
    }]
    /// Generated by [`link!`].
    ///
    /// It demonstrates two links sharing one compact target representation
    /// and a third independently represented link.
    ///
    /// # Methods
    ///
    /// - Construction: [`new`](#method.new).
    /// - Representation:
    ///   [`from_parts`](#method.from_parts),
    ///   [`into_parts`](#method.into_parts).
    /// - Primitive conversion:
    ///   [`from_prim`](#method.from_prim),
    ///   [`into_prim`](#method.into_prim),
    ///   [`try_from_usize`](#method.try_from_usize).
    /// - State: [`is_empty`](#method.is_empty).
    /// - Per-link access:
    ///   `get_<field>` *(`_prim`, `_usize`)*,
    ///   `has_<field>`.
    /// - Per-link mutation:
    ///   `set_<field>` *(`_prim`)*,
    ///   `clear_<field>`,
    ///   `with_<field>`,
    ///   `without_<field>`.
    pub LinkExample;
}
