
[workspace]

[package]
name = "board_arduino_due"
# version = "0.0.0"
edition = "2024"
publish = false

[dependencies.devela_micros]
path = "../../../../"
default-features = false
features = [
	"arduino_due",
	# "time",
	"unsafe_hint", "unsafe_mmio",
]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
panic = "abort"

[lints.cargo]
non_kebab_case_bins = "allow"
