# devela/examples/hw/mcu/esp32/s3_bringup/.cargo/config.toml

[build]
target = "xtensa-esp32s3-none-elf"

[target.xtensa-esp32s3-none-elf]
rustflags = [
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-L.",
    "-C", "link-arg=-Tlink.x",
]

[unstable]
build-std = ["core"]
