// devela/src/data/store/arena/string/_example.rs
//
//! Defines string arena examples.
//

use crate::arena_string;

arena_string! {
    [
        index: u8 + crate::NonMaxU8;
        cursor: u16 + crate::NonMaxU16;
    ]

    #[doc = crate::_tags!(example data_structure)]
    /// An example fixed-capacity UTF-8 string arena.
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaStringExample),
    }]
    /// Generated by [`arena_string!`].
    ///
    /// Stores strings contiguously as UTF-8 while addressing each retained
    /// string through a compact insertion-order handle.
    ///
    /// # Methods
    ///
    /// - Construction: [`new`](#method.new).
    /// - String capacity:
    ///   [`capacity`](#method.capacity), [`len`](#method.len),
    ///   [`is_empty`](#method.is_empty), [`remaining`](#method.remaining),
    ///   [`is_full`](#method.is_full).
    /// - Byte capacity:
    ///   [`byte_capacity`](#method.byte_capacity),
    ///   [`byte_len`](#method.byte_len),
    ///   [`byte_remaining`](#method.byte_remaining),
    ///   [`can_insert`](#method.can_insert).
    /// - Access:
    ///   [`contains`](#method.contains), [`get`](#method.get),
    ///   [`as_bytes`](#method.as_bytes).
    /// - Mutation: [`insert`](#method.insert).
    /// - Reclamation:
    ///   [`mark`](#method.mark), [`rollback`](#method.rollback),
    ///   [`clear`](#method.clear).
    /// - Iteration:
    ///   [`iter`](#method.iter), [`ids`](#method.ids),
    ///   [`entries`](#method.entries).
    pub ArenaStringExample;

    #[doc = crate::_tags!(example uid)]
    /// An index handle into [`ArenaStringExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaStringHandleExample),
        test_size_of(ArenaStringHandleExample = 1|8; niche Option),
    }]
    /// Generated by [`arena_string!`] and [`handle!`][crate::handle].
    ///
    #[doc = crate::_DOC_HANDLE_INDEX_METHODS!()]
    pub ArenaStringHandleExample;

    #[doc = crate::_tags!(example state)]
    /// A rollback mark for [`ArenaStringExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaStringMarkExample),
        test_size_of(ArenaStringMarkExample = 1|8; niche Option),
    }]
    /// Generated by [`arena_string!`].
    ///
    /// Created by [`ArenaStringExample::mark`]
    /// and consumed by [`ArenaStringExample::rollback`].
    pub ArenaStringMarkExample;
}

#[cfg(feature = "alloc")]
arena_string! {
    [
        index: u8 + crate::NonMaxU8;
        cursor: u16 + crate::NonMaxU16;
    ]

    #[doc = crate::_tags!(example data_structure)]
    /// An example allocating UTF-8 string arena.
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaStringAllocExample),
        #[cfg(target_pointer_width = "32")]
        test_size_of(ArenaStringAllocExample = 24|192; niche Option),
        #[cfg(target_pointer_width = "64")]
        test_size_of(ArenaStringAllocExample = 48|384; niche Option),
    }]
    /// Generated by [`arena_string!`].
    ///
    /// Its string and byte capacities describe storage available without
    /// reallocating. The arena may continue growing until either configured
    /// coordinate representation is exhausted.
    ///
    /// # Methods
    ///
    /// - Construction:
    ///   [`new`](#method.new), [`with_capacity`](#method.with_capacity).
    /// - String capacity:
    ///   [`capacity`](#method.capacity), [`len`](#method.len),
    ///   [`is_empty`](#method.is_empty), [`remaining`](#method.remaining),
    ///   [`is_full`](#method.is_full).
    /// - Byte capacity:
    ///   [`byte_capacity`](#method.byte_capacity),
    ///   [`byte_len`](#method.byte_len),
    ///   [`byte_remaining`](#method.byte_remaining),
    ///   [`can_insert`](#method.can_insert).
    /// - Access:
    ///   [`contains`](#method.contains), [`get`](#method.get),
    ///   [`as_bytes`](#method.as_bytes).
    /// - Mutation: [`insert`](#method.insert).
    /// - Reclamation:
    ///   [`mark`](#method.mark), [`rollback`](#method.rollback),
    ///   [`clear`](#method.clear).
    /// - Iteration:
    ///   [`iter`](#method.iter), [`ids`](#method.ids),
    ///   [`entries`](#method.entries).
    pub ArenaStringAllocExample: alloc;

    #[doc = crate::_tags!(example uid)]
    /// An index handle into [`ArenaStringAllocExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaStringAllocHandleExample),
        test_size_of(ArenaStringAllocHandleExample = 1|8; niche Option),
    }]
    /// Generated by [`arena_string!`] and [`handle!`][crate::handle].
    ///
    #[doc = crate::_DOC_HANDLE_INDEX_METHODS!()]
    pub ArenaStringAllocHandleExample;

    #[doc = crate::_tags!(example state)]
    /// A rollback mark for [`ArenaStringAllocExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaStringAllocMarkExample),
        #[cfg(target_pointer_width = "32")]
        test_size_of(ArenaStringAllocMarkExample = 4|32; niche !Option),
        #[cfg(target_pointer_width = "64")]
        test_size_of(ArenaStringAllocMarkExample = 8|64; niche !Option),
    }]
    /// Generated by [`arena_string!`].
    pub ArenaStringAllocMarkExample;
}
