# devela_bridge manifest
# ==============================================================================
[package]
name = "devela_bridge"
description = "Foreign-language bindings and ABI bridges for devela"
repository = "https://github.com/andamira/devela/tree/main/crates/bridge"
# documentation = "https://docs.rs/devela_bridge"

version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false # TEMP
include = [
	"/Cargo.toml",
	"/README.md",
	"/LICENSE*",
	"/build.sh",

	"/abi/*.abi",

	"/src/**/*.rs",

	"/pkg/c/*.h",
	"/pkg/odin/**/*.odin",

	"/examples/README.md",
	"/examples/run_all.sh",
	"/examples/*/*.c",
	"/examples/*/*.odin",
	"/examples/*/run.sh",

	## exclusions
	"!**/_wip/**",
]

[lib]
crate-type = ["rlib"]

[features]

__bindgen = []

alloc = ["devela/alloc"]
std = ["devela/std"]

linux = ["devela/linux"]
term = ["devela/term"]
event = ["devela/event"]

[dependencies.devela]
path = "../devela"
# features = ["unsafe_ffi"] # IMPROVE

[[bin]]
name = "bridge_bindgen"
path = "src/bin/bridge_bindgen.rs"
required-features = ["__bindgen"]
