# devela_bridge manifest
# ==============================================================================

[lib]
crate-type = ["rlib"]
path = "src/_.rs"
bench = false

[package]
name = "devela_bridge"
description = "Foreign-language bindings and ABI bridges for devela"
documentation = "https://docs.rs/devela_bridge"
repository = "https://github.com/andamira/devela/tree/main/crates/bridge"
rust-version.workspace = true
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
publish = false # TEMP
include = [
	"/Cargo.toml",
	"/README.md",
	"/LICENSE*",
	"/build.sh",
	#
	"/abi/*.abi",
	#
	"/src/**/*.rs",
	#
	"/pkg/c/*.h",
	"/pkg/odin/**/*.odin",
	#
	"/examples/README.md",
	"/examples/run_all.sh",
	"/examples/*/*.c",
	"/examples/*/*.odin",
	"/examples/*/run.sh",
	## exclusions
	"!**/_wip/**",
]

[package.metadata.docs.rs]
no-default-features = true
features = ["_docs", "__publish"]
rustc-args = [
    "--cfg", "nightly_doc",
    "--cfg", "nightly",
]
rustdoc-args = [
    "--cfg", "nightly_doc",
    "--cfg", "nightly",
    "--generate-link-to-definition",
    "--html-in-header", "./src/_doc/header.html",
]


[features]

#* Development features *#
# ------------------------------------------------------------------------------

__bindgen = [] # compile src/bin/bridge_bindgen.rs
__dbg = ["devela/__dbg"] # shows extra debugging information
__publish = ["devela/__publish"] # enabled when publishing to crates.io or docs.rs
__docs_internal = ["devela/__docs_internal"] # enables documentation for internal items
__exclude_test = [] # excludes specific examples from being tested


#* Environment features *#
# ------------------------------------------------------------------------------

alloc = ["devela/alloc"]
std = ["devela/std"]

#* Module features *#
# ------------------------------------------------------------------------------

all = ["term", "event"]

linux = ["devela/linux"] # NOTE enables unsafe
term = ["devela/term"]
event = ["devela/event"]


#* Safety features *#
# ------------------------------------------------------------------------------

# safest = ["safe", "devela/safest"]
#
# safe = ["devela/safe"] # RETHINK
#
# unsafe = []


#* Scope features *#
# ------------------------------------------------------------------------------


#* _docs scope *#
# ---------------

_docs = ["all", "std", "linux"] # unsafe


[dependencies]
# ==============================================================================
devela = { workspace = true }
# features = ["unsafe_ffi"] # IMPROVE


[badges]
# ==============================================================================
maintenance.status = "experimental"

[lints]
workspace = true


# examples inside /examples/*
# ==============================================================================
# [[example]]
# name = ""


# binaries inside /src/bin/*
# ==============================================================================
[[bin]]
name = "bridge_bindgen"
path = "src/bin/bridge_bindgen.rs"
required-features = ["__bindgen"]

