// devela_base_core::data::handle
//
//! Defines [`define_handle!`] macro.
//

#[cfg(any(doc, test))]
define_handle! {
    #[doc = crate::_TAG_EXAMPLE!()]
    /// An example lightweight, copyable handle, generated by [`define_handle!`].
    pub ExampleHandle
}

/// Defines a custom handle type.
///
/// A *handle* is a lightweight, copyable semantic reference that identifies
/// an entry within a managed collection, such as an arena, list, or graph.
/// It carries just enough information to locate the data—usually an offset,
/// length, or index—without owning it.
///
/// Handles form the connective tissue of the data layer,
/// acting as bridges between raw storage and logical structure.
///
/// # Examples
/// See also [`ExampleHandle`].
/// ```
/// # use crate::define_handle;
/// define_handle! {
///     /// A custom handle.
///     pub ArenaHandle
/// }
/// ```
#[cfg_attr(cargo_primary_package, doc(hidden))]
#[macro_export]
macro_rules! define_handle {
    // Point of entry, defines the names
    (
    $(#[$handle_attr:meta])*
    $vis:vis $Handle:ident
    ) => {
        $crate::define_handle![%handle $(#[$handle_attr])* $vis $Handle];
    };
    // calls the necessary arms in order.
    (%handle $(#[$handle_attr:meta])* $vis:vis $Handle:ident) => { $crate::paste! {
        $crate::define_handle![%main
            $(#[$handle_attr])* $vis $Handle
        ];
        // #[cfg(test)]
        // $crate::define_handle![%tests $Handle, [<test_ $Handle>]];
    }};
    (%main $(#[$handle_attr:meta])* $vis:vis $Handle:ident) => {
        $(#[$handle_attr])*
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        $vis struct $Handle {
            offset: usize,
            len: usize,
        }

        // Fundamental methods.
        #[allow(dead_code)]
        impl $Handle {
            #[inline(always)]
            /// Returns a new handle.
            $vis const fn new(offset: usize, len: usize) -> Self {
                Self { offset, len }
            }

            #[inline(always)]
            /// Returns the length of the stored data.
            #[allow(clippy::len_without_is_empty)]
            $vis const fn len(self) -> usize { self.len }

            #[inline(always)]
            /// Returns the offset of the stored data.
            $vis const fn offset(self) -> usize { self.offset }
        }
    };
}
#[doc(inline)]
pub use define_handle;
