// devela/src/geom/affine/simplex/_.rs
//
//! Minimal affine cells generated by ordered points.
//

crate::mods_in! {
    #[cfg(test)]
    mod _test;

    mod define;
    mod facet;
}
crate::mods_out! { // _mods
    _mods {
        pub use super::{
            define::Simplex,
            facet::{SimplexFacetView, SimplexFacetIter},
        };
    }
}
