// devela/src/geom/affine/define.rs
//
//! Defines [`Simplex`].
//

use crate::{Point, SimplexFacetIter, SimplexFacetView, is};

#[doc = crate::_tags!(geom)]
/// An ordered, possibly degenerate simplex in `D`-dimensional affine space.
#[doc = crate::_doc_meta!{location("geom/affine")}]
///
/// A simplex is generated by `V` ordered [`Point`]s. Its dimension implied by
/// the vertex count is `V - 1`; therefore a structurally valid simplex requires:
///
/// - at least one vertex: `V > 0`,
/// - no more than `D + 1` vertices: `V - 1 <= D`.
///
/// The vertex order is significant. It can later determine orientation,
/// facet signs, winding, interpolation coordinates, and oriented boundaries.
///
/// # Degeneracy
///
/// This type does not verify that its vertices are affinely independent.
/// Consequently, it can represent degenerate simplices whose actual affine
/// dimension is smaller than `V - 1`.
///
/// Degeneracy is deliberately treated as a geometric property to query, not
/// as a storage invariant. This keeps construction generic over scalar types
/// and independent of matrix, rank, tolerance, and solver facilities.
///
/// # Dimensions
///
/// `D` is the dimension of the ambient affine space.
///
/// `V` is the number of stored vertices:
/// - `V = 1`: point simplex,
/// - `V = 2`: segment simplex,
/// - `V = 3`: triangle simplex,
/// - `V = 4`: tetrahedral simplex.
///
/// Empty simplices are not represented.
///
/// # Example
/// ```
/// # use devela::{Point, Simplex};
/// let triangle = Simplex::<i32, 2, 3>::new([
///     Point::new([0, 0]),
///     Point::new([4, 0]),
///     Point::new([0, 3]),
/// ]);
///
/// assert_eq!(triangle.dimension(), 2);
/// assert_eq!(triangle.codimension(), 0);
/// assert!(triangle.is_full_dimensional());
/// assert_eq!(triangle.vertex(1), Some(&Point::new([4, 0])));
/// ```
#[must_use]
#[non_exhaustive] // prevent downstream struct literals to enforce constructor invariants
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Simplex<T, const D: usize, const V: usize> {
    /// The ordered vertices generating this simplex.
    pub vertices: [Point<T, D>; V],
}

#[rustfmt::skip]
impl<T, const D: usize, const V: usize> Simplex<T, D, V> {
    /// The dimension of the ambient affine space.
    pub const AMBIENT_DIMENSION: usize = D;
    /// The number of stored vertices.
    pub const VERTEX_COUNT: usize = V;
    /// Creates a simplex from its ordered vertices.
    ///
    /// This validates only the relationship between `D` and `V`. It does not
    /// test whether the vertices are affinely independent.
    ///
    /// # Panics
    ///
    /// Panics if:
    ///
    /// - `V == 0`, or
    /// - `V - 1 > D`.
    pub const fn new(vertices: [Point<T, D>; V]) -> Self {
        assert!(V > 0, "a simplex requires at least one vertex");
        assert!(V - 1 <= D, "the simplex dimension exceeds its ambient dimension");
        Self { vertices }
    }
    /// Returns the dimension implied by the number of vertices.
    ///
    /// This is `V - 1`. A degenerate simplex can have a smaller actual affine
    /// dimension.
    #[must_use]
    pub const fn dimension(&self) -> usize { V - 1 }

    /// Returns the simplex codimension in its ambient space.
    ///
    /// This is `D - (V - 1)`.
    #[must_use]
    pub const fn codimension(&self) -> usize { D - (V - 1) }

    /// Returns whether the simplex dimension equals the ambient dimension.
    ///
    /// This describes its structural dimensions only. A full-dimensional
    /// simplex can still be geometrically degenerate.
    #[must_use]
    pub const fn is_full_dimensional(&self) -> bool { V - 1 == D }

    /* vertex */

    /// Returns the vertex at `index`, or `None` when it is out of bounds.
    #[must_use]
    pub const fn vertex(&self, index: usize) -> Option<&Point<T, D>> {
        is! { index < V, Some(&self.vertices[index]), None }
    }
    /// Returns the vertex at `index` mutably, or `None` when it is out of bounds.
    pub const fn vertex_mut(&mut self, index: usize) -> Option<&mut Point<T, D>> {
        is! { index < V, Some(&mut self.vertices[index]), None }
    }

    /// Maps every ordered vertex into another point type.
    ///
    /// The ambient dimension and vertex count remain unchanged.
    pub fn map_vertices<U>(self, map: impl FnMut(Point<T, D>) -> Point<U, D>) -> Simplex<U, D, V> {
        Simplex { vertices: self.vertices.map(map), }
    }

    /* facet */

    /// Returns the number of representable facets.
    ///
    /// Every simplex with at least two vertices has one facet opposite each
    /// vertex. A point simplex returns zero because empty facets are not
    /// represented.
    #[must_use]
    pub const fn facet_count(&self) -> usize {
        if V > 1 { V } else { 0 }
    }
    /// Returns the facet opposite vertex `omitted`.
    ///
    /// Returns `None` when `omitted` is out of bounds or this is a point
    /// simplex, whose empty facet is not represented.
    #[must_use]
    pub const fn facet(
        &self,
        omitted: usize,
    ) -> Option<SimplexFacetView<'_, T, D, V>> {
        if V > 1 && omitted < V {
            Some(SimplexFacetView {
                simplex: self,
                omitted,
            })
        } else {
            None
        }
    }
    /// Iterates over the facets in omitted-vertex order.
    pub const fn facets(&self) -> SimplexFacetIter<'_, T, D, V> {
        SimplexFacetIter {
            simplex: self,
            front: 0,
            back: self.facet_count(),
        }
    }
}
