// devela/src/geom/affine/simplex/mod.rs
//
//! Minimal affine cells generated by ordered points.
//

#[cfg(test)]
mod _test;

mod define;
mod facet;

crate::structural_mods! { // _mods
    _mods {
        pub use super::{
            define::Simplex,
            facet::{SimplexFacetView, SimplexFacetIter},
        };
    }
}
