// devela/src/data/topol/graph/csr/_test.rs

use crate::{NonMaxU8, NonMaxU16, graph_csr};

graph_csr! {
    [
        vertex: u8 + NonMaxU8;
        edge: u16 + NonMaxU16;
    ]

    #[doc = crate::_tags!(example data_structure topol)]
    /// An example static CSR graph.
    #[doc = crate::_doc_meta!{
        location("data/topol/graph", struct GraphCsrExample),
        test_size_of(__: GraphCsrExample<4, 4> = 12|96; niche Option),
    }]
    /// Generated by [`graph_csr!`].
    ///
    /// # Methods
    ///
    /// - Construction and representation:
    ///   [`from_parts`](#method.from_parts),
    ///   [`as_parts`](#method.as_parts),
    ///   [`into_parts`](#method.into_parts).
    /// - Size:
    ///   [`vertex_count`](#method.vertex_count),
    ///   [`edge_count`](#method.edge_count),
    ///   [`is_empty`](#method.is_empty).
    /// - Handles:
    ///   [`vertex`](#method.vertex), [`edge`](#method.edge),
    ///   [`contains_vertex`](#method.contains_vertex),
    ///   [`contains_edge`](#method.contains_edge).
    /// - Adjacency:
    ///   [`out_edge_bounds`](#method.out_edge_bounds),
    ///   [`edge_target`](#method.edge_target).
    /// - Queries:
    ///   [`has_edge`](#method.has_edge),
    ///   [`out_degree`](#method.out_degree),
    ///   [`in_degree`](#method.in_degree),
    ///   [`is_reachable`](#method.is_reachable) *([`_in`](#method.is_reachable_in))*,
    ///   [`is_acyclic`](#method.is_acyclic) *([`_in`](#method.is_acyclic_in))*.
    /// - Iteration:
    ///   [`out_edges`](#method.out_edges),
    ///   [`neighbors`](#method.neighbors).
    pub GraphCsrExample;

    #[doc = crate::_tags!(example uid topol)]
    /// A vertex handle into [`GraphCsrExample`].
    #[doc = crate::_doc_meta!{
        location("data/topol/graph", struct GraphCsrVertexExample),
        test_size_of(GraphCsrVertexExample = 1|8; niche Option),
    }]
    /// Generated by [`graph_csr!`].
    pub GraphCsrVertexExample;

    #[doc = crate::_tags!(example uid topol)]
    /// An edge handle into [`GraphCsrExample`].
    #[doc = crate::_doc_meta!{
        location("data/topol/graph", struct GraphCsrEdgeExample),
        test_size_of(GraphCsrEdgeExample = 2|16; niche Option),
    }]
    /// Generated by [`graph_csr!`].
    pub GraphCsrEdgeExample;
}

#[cfg(feature = "alloc")]
graph_csr! {
    [
        vertex: u8 + NonMaxU8;
        edge: u16 + NonMaxU16;
    ]

    #[doc = crate::_tags!(example data_structure topol)]
    /// An example allocating CSR graph.
    #[doc = crate::_doc_meta!{
        location("data/topol/graph", struct GraphCsrAllocExample),
        #[cfg(target_pointer_width = "32")]
        test_size_of(GraphCsrAllocExample = 24|192; niche Option),
        #[cfg(target_pointer_width = "64")]
        test_size_of(GraphCsrAllocExample = 48|384; niche Option),
    }]
    /// Generated by [`graph_csr!`].
    ///
    /// # Methods
    ///
    /// - Construction and representation:
    ///   [`from_parts`](#method.from_parts),
    ///   [`as_parts`](#method.as_parts),
    ///   [`into_parts`](#method.into_parts).
    /// - Size:
    ///   [`vertex_count`](#method.vertex_count),
    ///   [`edge_count`](#method.edge_count),
    ///   [`is_empty`](#method.is_empty).
    /// - Handles:
    ///   [`vertex`](#method.vertex), [`edge`](#method.edge),
    ///   [`contains_vertex`](#method.contains_vertex),
    ///   [`contains_edge`](#method.contains_edge).
    /// - Adjacency:
    ///   [`out_edge_bounds`](#method.out_edge_bounds),
    ///   [`edge_target`](#method.edge_target).
    /// - Queries:
    ///   [`has_edge`](#method.has_edge),
    ///   [`out_degree`](#method.out_degree),
    ///   [`in_degree`](#method.in_degree),
    ///   [`is_reachable_in`](#method.is_reachable_in),
    ///   [`is_acyclic_in`](#method.is_acyclic_in).
    /// - Iteration:
    ///   [`out_edges`](#method.out_edges),
    ///   [`neighbors`](#method.neighbors).
    pub GraphCsrAllocExample: alloc;

    #[doc = crate::_tags!(example uid topol)]
    /// A vertex handle into [`GraphCsrAllocExample`].
    #[doc = crate::_doc_meta!{
        location("data/topol/graph", struct GraphCsrAllocVertexExample),
        test_size_of(GraphCsrAllocVertexExample = 1|8; niche Option),
    }]
    /// Generated by [`graph_csr!`].
    pub GraphCsrAllocVertexExample;

    #[doc = crate::_tags!(example uid topol)]
    /// An edge handle into [`GraphCsrAllocExample`].
    #[doc = crate::_doc_meta!{
        location("data/topol/graph", struct GraphCsrAllocEdgeExample),
        test_size_of(GraphCsrAllocEdgeExample = 2|16; niche Option),
    }]
    /// Generated by [`graph_csr!`].
    pub GraphCsrAllocEdgeExample;
}
