//

#[cfg(feature = "_docs_examples")]
crate::divisor! {
    #[doc = crate::_tags!(example num)]
    /// An example divisor helper generated by [`divisor!`][crate::divisor].
    #[doc = crate::_doc_meta!{
        location("num/dom/int", struct DivisorExample),
    }]
    /// This type exists to document the methods produced by the macro.
    ///
    /// Implemented for [`i32`](#impl-DivisorExample<i32>)
    /// and [`u32`](#impl-DivisorExample<u32>).
    /// *(The macro supports all integer primitives)*
    pub struct DivisorExample:<> impl (i32, u32)
}

#[cfg(test)]
mod _test {
    #![allow(unused)]

    use crate::divisor;

    #[test]
    fn divisor() {
        // individual separate
        divisor![pub struct DivI8: (i8)];
        divisor![impl DivI8: (i8)];
        // individual combined
        divisor![pub struct DivU8: (u8) impl];

        // generic separate
        divisor![pub struct DivA:<>];
        divisor![impl DivA:<> (i8, u32, u128, usize, isize)];
        // generic combined
        divisor![pub struct DivB:<> impl (i8, u32, u128, usize, isize)];
    }
}
