//
//! Defines [`divisor!`].
//

#[doc = crate::_tags!(construction code num)]
/// Defines a divisor struct for faster division and modulo operations.
#[doc = crate::_doc_meta!{
    location("num/dom/int", macro divisor),
}]
/// This macro generates a *divisor helper type* that precomputes information
/// about a divisor to speed up repeated division and remainder operations.
///
/// The macro supports both:
/// - **Concrete divisor types**, bound to a single primitive integer.
/// - **Generic divisor shells**, which can later be implemented for multiple primitive integers.
///
/// ---
///
/// ## Syntax overview
///
/// The macro follows a common grammar:
/// ```text
/// struct Name : Spec [impl (targets)]
/// impl   Name : Spec (targets)
/// ```
///
/// Where:
/// - `Name` is the type name
/// - `Spec` is either:
///   - `(T)`   for a concrete primitive type
///   - `<>`    to declare a generic divisor shell
/// - `targets` is a comma-separated list of primitive integer types
///
/// ## Examples
/// ```
/// use devela::divisor;
///
/// // Define and implement a divisor type for a single primitive:
/// divisor![pub struct DivU8 : (u8) impl];
/// let d = DivU8::new(5).unwrap();
/// let x = d.div_of(42);
///
/// // Define a generic divisor type without implementations:
/// divisor![pub struct Div : <>];
///
/// // Attach implementations to a previously defined generic divisor:
/// divisor![impl Div : <> (i8, u32, usize)];
///
/// // Define a generic divisor and immediately implement it:
/// divisor![pub struct FastDiv : <> impl (i8, u32, u128, usize)];
/// ```
/// See [`DivisorExample`]
/// for the fully documented methods generated by this macro.
///
/// [`DivisorExample`]: crate::DivisorExample
///
/// ---
///
/// ## Notes
/// - All implementations are resolved at compile time.
/// - Only supported integer primitives are accepted as targets.
/// - Passing an unsupported type results in a compile-time error.
/// - Division by zero is checked when constructing a divisor.
#[doc = crate::_doc_vendor!("quickdiv")]
#[macro_export]
#[cfg_attr(cargo_primary_package, doc(hidden))]
macro_rules! divisor· {
    (
    /* public macro arms */

        // new individual definition + impl
        $(#[$attr:meta])*
        $vis:vis struct $Name:ident : ($T:ident) impl
    ) => {
        $(#[$attr])* #[must_use]
        #[derive(Clone, Copy)]
        $vis struct $Name { inner: $crate::__Divisor<$T> }
        $crate::divisor!(impl $Name : ($T));
    };
    (
        // new generic definition + impl(s)
        $(#[$attr:meta])* $vis:vis struct $Name:ident : <> impl ($($T:ident),+)
    ) => {
        $(#[$attr])* #[must_use]
        #[derive(Clone, Copy)]
        $vis struct $Name<T> { inner: $crate::__Divisor<T> }
        $( $crate::__divisor!(%impl $Name<$T>, $Name; $T); )+
    };
    (
        // new individual definition
        $(#[$attr:meta])*
        $vis:vis struct $Name:ident : ($T:ident)
    ) => {
        $(#[$attr])* #[must_use]
        #[derive(Clone, Copy)]
        $vis struct $Name { inner: $crate::__Divisor<$T> }
    };
    (
        // new generic definition
        $(#[$attr:meta])* $vis:vis struct $Name:ident : <>
    ) => {
        $(#[$attr])* #[must_use]
        #[derive(Clone, Copy)]
        $vis struct $Name<T> { inner: $crate::__Divisor<T> }
    };
    (
        // individual impl
        impl $Name:ident : ($T:ident)
    ) => {
        $crate::__divisor!(%impl $Name, $Name; $T);
    };
    (
        // generic impl(s)
        impl $Name:ident : <> ($($T:ident),+)
    ) => {
        $( $crate::__divisor!(%impl $Name<$T>, $Name; $T); )+
    };
}
#[doc(inline)]
pub use divisor· as divisor;
