#!/bin/sh
#
# A simple wrapper to enable native CPU optimizations for Cargo commands.
#
# # Install
#   Copy this script to a directory in your PATH. For example:
#   $ cp ./tools/cargo-native ~/.cargo/bin/cargo-native
#
# # Usage
#   $ cargo native <cargo-command> [args...]
#
# # Examples
#   $ cargo native build
#   $ cargo native test --release
#   $ cargo native re example_name
#   $ cargo +nightly native nd -F _docs
#
# FIX:NOTE: this doesn't include any nightly flags

# Default flags for the "native" profile
#
# In sync with .cargo/config.toml
FLAGS="-C target-cpu=native"
DOCFLAGS="--html-in-header ./src/_doc/header.html -C target-cpu=native"

# Shift the first argument ("native") and pass the rest to Cargo
shift

# Set RUSTFLAGS and execute the Cargo command
RUSTDOCFLAGS="$DOCFLAGS" RUSTFLAGS="$FLAGS" exec cargo "$@"
