// devela/src/data/store/arena/bytes/_example.rs
//
//! Defines [`ArenaBytesExample`], [`ArenaBytesHandleExample`], [`ArenaBytesMarkExample`].
//

use crate::arena_bytes;

arena_bytes! {
    [cursor: u8 + crate::NonMaxU8;]

    #[doc = crate::_tags!(example data_structure)]
    /// An example byte arena.
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaBytesExample),
        test_size_of(__: ArenaBytesExample<63> = 64|512; niche !Option),
    }]
    /// Generated by [`arena_bytes!`].
    ///
    /// # Methods
    ///
    /// - Construction: [`new`](#method.new).
    /// - Capacity:
    ///   [`capacity`](#method.capacity), [`len`](#method.len),
    ///   [`is_empty`](#method.is_empty), [`is_full`](#method.is_full),
    ///   [`remaining`](#method.remaining), [`can_write`](#method.can_write).
    /// - Whole storage:
    ///   [`as_bytes`](#method.as_bytes) *([_mut](#method.as_bytes_mut))*,
    ///   [`eq`](#method.eq).
    /// - Byte spans:
    ///   [`push_filled`](#method.push_filled),
    ///   [`push_zeroed`](#method.push_zeroed),
    ///   [`push_bytes`](#method.push_bytes),
    ///   [`read_bytes`](#method.read_bytes) *([_mut](#method.read_bytes_mut))*,
    ///   [`replace_bytes`](#method.replace_bytes).
    /// - Strings:
    ///   [`push_str`](#method.push_str),
    ///   [`read_str`](#method.read_str) *([_mut](#method.read_str_mut))*,
    ///   [`replace_str`](#method.replace_str).
    /// - Single bytes:
    ///   [`push_byte`](#method.push_byte),
    ///   [`read_byte`](#method.read_byte) *([_mut](#method.read_byte_mut))*,
    ///   [`replace_byte`](#method.replace_byte).
    /// - Repeated views:
    ///   [`view_bytes`](#method.view_bytes) *([_mut](#method.view_bytes_mut))*.
    /// - Reclamation:
    ///   [`mark`](#method.mark), [`rollback`](#method.rollback),
    ///   [`truncate_last`](#method.truncate_last),
    ///   [`pop_into`](#method.pop_into), [`clear`](#method.clear).
    /// - Primitive values: `push_*`, `read_*` and `replace_*` for
    ///   booleans, characters, integers and floating-point primitives.
    pub ArenaBytesExample;

    #[doc = crate::_tags!(example uid)]
    /// An example handle into [`ArenaBytesExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaBytesHandleExample),
        test_size_of(ArenaBytesHandleExample = 2|16; niche Option),
    }]
    /// Generated by [`arena_bytes!`] and [`handle_span!`][crate::handle_span].
    ///
    /// # Methods
    ///
    /// - Construction:
    ///   [`new`](#method.new), [`from_prim`](#method.from_prim),
    ///   [`try_from_usize`](#method.try_from_usize).
    /// - Decomposition:
    ///   [`into_parts`](#method.into_parts), [`into_prim`](#method.into_prim).
    /// - Offset:
    ///   [`offset`](#method.offset), [`offset_prim`](#method.offset_prim),
    ///   [`offset_usize`](#method.offset_usize).
    /// - Length:
    ///   [`len`](#method.len), [`len_prim`](#method.len_prim),
    ///   [`len_usize`](#method.len_usize), [`is_empty`](#method.is_empty).
    pub ArenaBytesHandleExample;

    #[doc = crate::_tags!(example state)]
    /// An example memory arena mark.
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaBytesMarkExample),
        test_size_of(ArenaBytesMarkExample = 1|8; niche !Option),
    }]
    /// Generated by [`arena_bytes!`].
    ///
    /// Created by [`ArenaBytesExample::mark`]
    /// and consumed by [`ArenaBytesExample::rollback`].
    pub ArenaBytesMarkExample;
}

#[cfg(feature = "alloc")]
arena_bytes! {
    [cursor: u8 + crate::NonMaxU8;]

    #[doc = crate::_tags!(example data_structure)]
    /// An example allocating byte arena.
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaBytesAllocExample),
        #[cfg(target_pointer_width = "32")]
        test_size_of(ArenaBytesAllocExample = 12|96; niche Option),
        #[cfg(target_pointer_width = "64")]
        test_size_of(ArenaBytesAllocExample = 24|192; niche Option),
    }]
    /// Generated by [`arena_bytes!`].
    ///
    /// Its `capacity` and `remaining` values describe the bytes writable
    /// without reallocating. The arena may continue growing until its
    /// configured byte-coordinate range is exhausted.
    ///
    /// # Methods
    ///
    /// - Construction:
    ///   [`new`](#method.new), [`with_capacity`](#method.with_capacity).
    /// - Capacity:
    ///   [`capacity`](#method.capacity), [`len`](#method.len),
    ///   [`is_empty`](#method.is_empty), [`is_full`](#method.is_full),
    ///   [`remaining`](#method.remaining), [`can_write`](#method.can_write).
    /// - Whole storage:
    ///   [`as_bytes`](#method.as_bytes) *([_mut](#method.as_bytes_mut))*,
    ///   [`eq`](#method.eq).
    /// - Byte spans:
    ///   [`push_filled`](#method.push_filled),
    ///   [`push_zeroed`](#method.push_zeroed),
    ///   [`push_bytes`](#method.push_bytes),
    ///   [`read_bytes`](#method.read_bytes) *([_mut](#method.read_bytes_mut))*,
    ///   [`replace_bytes`](#method.replace_bytes).
    /// - Strings:
    ///   [`push_str`](#method.push_str),
    ///   [`read_str`](#method.read_str) *([_mut](#method.read_str_mut))*,
    ///   [`replace_str`](#method.replace_str).
    /// - Single bytes:
    ///   [`push_byte`](#method.push_byte),
    ///   [`read_byte`](#method.read_byte) *([_mut](#method.read_byte_mut))*,
    ///   [`replace_byte`](#method.replace_byte).
    /// - Repeated views:
    ///   [`view_bytes`](#method.view_bytes) *([_mut](#method.view_bytes_mut))*.
    /// - Reclamation:
    ///   [`mark`](#method.mark), [`rollback`](#method.rollback),
    ///   [`truncate_last`](#method.truncate_last),
    ///   [`pop_into`](#method.pop_into), [`clear`](#method.clear).
    /// - Primitive values: `push_*`, `read_*` and `replace_*` for
    ///   booleans, characters, integers and floating-point primitives.
    pub ArenaBytesAllocExample: alloc;

    #[doc = crate::_tags!(example uid)]
    /// An example span handle into [`ArenaBytesAllocExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaBytesAllocHandleExample),
        test_size_of(ArenaBytesAllocHandleExample = 2|16; niche Option),
    }]
    /// Generated by [`arena_bytes!`] and [`handle_span!`][crate::handle_span].
    ///
    /// # Methods
    ///
    /// - Construction:
    ///   [`new`](#method.new), [`from_prim`](#method.from_prim),
    ///   [`try_from_usize`](#method.try_from_usize).
    /// - Decomposition:
    ///   [`into_parts`](#method.into_parts), [`into_prim`](#method.into_prim).
    /// - Offset:
    ///   [`offset`](#method.offset), [`offset_prim`](#method.offset_prim),
    ///   [`offset_usize`](#method.offset_usize).
    /// - Length:
    ///   [`len`](#method.len), [`len_prim`](#method.len_prim),
    ///   [`len_usize`](#method.len_usize), [`is_empty`](#method.is_empty).
    pub ArenaBytesAllocHandleExample;

    #[doc = crate::_tags!(example state)]
    /// An example rollback position within [`ArenaBytesAllocExample`].
    #[doc = crate::_doc_meta!{
        location("data/store/arena", struct ArenaBytesAllocMarkExample),
        test_size_of(ArenaBytesAllocMarkExample = 1|8; niche !Option),
    }]
    /// Generated by [`arena_bytes!`].
    ///
    /// Created by [`ArenaBytesAllocExample::mark`]
    /// and consumed by [`ArenaBytesAllocExample::rollback`].
    pub ArenaBytesAllocMarkExample;
}
