# gets linux errno.h values on each target,
# creates rust files with constants
# and uploads them as artifacts.

name: get errno.h values as rust constants

on:
  workflow_dispatch:

jobs:
  errno:
    name: "get errno.h values for ${{ matrix.config.target }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        config:
          - {target: x86_64-unknown-linux-gnu, docker_image: amd64/ubuntu}
          - {target: i686-unknown-linux-gnu, docker_image: i386/ubuntu}
          - {target: aarch64-unknown-linux-gnu, docker_image: arm64v8/ubuntu}
          - {target: armv7-unknown-linux-gnueabihf, docker_image: arm32v7/ubuntu}
          - {target: riscv64gc-unknown-linux-gnu, docker_image: riscv64/ubuntu}
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "get errno.h values"
        run: |
            docker run --rm -v $PWD:/workdir -w /workdir ${{ matrix.config.docker_image }} /bin/bash -c "
              apt-get update && apt-get install -y apt-utils && apt-get install -y gcc && \
              ./tools/get_errno.sh ${{ matrix.config.target }}
            "
      - name: "Upload errno files"
        uses: actions/upload-artifact@v3
        with:
          name: "exported_errno_rust_consts"
          path: errno_${{ matrix.config.target }}.rs
          if-no-files-found: error

