permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

name: "no-std"
jobs:
  #
  nostd:
    name: "${{ matrix.target }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [thumbv7m-none-eabi, aarch64-unknown-none]
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
        with:
            submodules: true

      - name: "Install stable"
        uses: dtolnay/rust-toolchain@stable

      - name: "rustup target add ${{ matrix.target }}"
        run: rustup target add ${{ matrix.target }}

      - name: "cargo check -F full,no_std,unsafe"
        run: cargo check --target ${{ matrix.target }} -F full,no_std,unsafe

      - name: "cargo check -F full,no_std,safe"
        run: cargo check --target ${{ matrix.target }} -F full,no_std,safe

  #
  alloc:
    name: "${{ matrix.target }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [thumbv7m-none-eabi, aarch64-unknown-none]
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
        with:
            submodules: true

      - name: "Install stable"
        uses: dtolnay/rust-toolchain@stable

      - name: "rustup target add ${{ matrix.target }}"
        run: rustup target add ${{ matrix.target }}

      - name: "cargo check alloc -F full,alloc,unsafe"
        run: cargo check --target ${{ matrix.target }} -F full,alloc,unsafe

      - name: "cargo check alloc -F full,alloc,safe"
        run: cargo check --target ${{ matrix.target }} -F full,alloc,safe
