permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

name: "no-std"
jobs:
  #
  nostd:
    name: "${{ matrix.target }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [
          i686-unknown-uefi,
          thumbv7m-none-eabi,
          aarch64-unknown-none,
          riscv32imac-unknown-none-elf,
          riscv64imac-unknown-none-elf,
          wasm32-unknown-unknown,
        ]
    steps:
      - name: "checkout"
        uses: actions/checkout@v5
        with:
            submodules: true

      - name: "Install stable"
        uses: dtolnay/rust-toolchain@stable

      - name: "rustup target add ${{ matrix.target }}"
      # run: rustup target add ${{ matrix.target }}
        run: |
          for i in {1..5}; do
            rustup target add ${{ matrix.target }} && break
            echo "Attempt $i failed, retrying in 5 seconds..."; sleep 5
          done

      - name: "cargo check -F all,no_std,unsafe"
        run: cargo check --target ${{ matrix.target }} -F all,no_std,unsafe

      - name: "cargo check -F all,no_std,safe"
        run: cargo check --target ${{ matrix.target }} -F all,no_std,safe

  #
  alloc:
    name: "${{ matrix.target }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [
          i686-unknown-uefi,
          thumbv7m-none-eabi,
          aarch64-unknown-none,
          riscv32imac-unknown-none-elf,
          riscv64imac-unknown-none-elf,
          wasm32-unknown-unknown,
        ]
    steps:
      - name: "checkout"
        uses: actions/checkout@v5
        with:
            submodules: true

      - name: "Install stable"
        uses: dtolnay/rust-toolchain@stable

      - name: "rustup target add ${{ matrix.target }}"
      # run: rustup target add ${{ matrix.target }}
        run: |
          for i in {1..5}; do
            rustup target add ${{ matrix.target }} && break
            echo "Attempt $i failed, retrying in 5 seconds..."; sleep 5
          done

      - name: "cargo check alloc -F all,alloc,unsafe"
        run: cargo check --target ${{ matrix.target }} -F all,alloc,unsafe

      - name: "cargo check alloc -F all,alloc,safe"
        run: cargo check --target ${{ matrix.target }} -F all,alloc,safe
